type Translations = Record<string, string>

const en: Translations = {
  // Nav
  'nav.orders': 'Orders',
  'nav.companies': 'Companies',
  'nav.statistics': 'Statistics',
  'nav.wines': 'Wines',
  'nav.wineOrders': 'Wine Orders',
  'nav.menuItems': 'Menu Items',
  'nav.masterclass': 'Masterclass',
  'nav.content': 'Site Content',
  'nav.settings': 'Settings',
  'nav.adminTag': 'Admin',
  'nav.platform': 'Platform',
  'nav.signOut': 'Sign out',

  // Settings — Admin Panel Language section
  'settings.adminLanguage.sectionTitle': 'Admin Panel Language',
  'settings.adminLanguage.sectionHint': 'Language used throughout this admin panel. Set once here — there is no in-panel switcher.',
  'settings.adminLanguage.fieldLabel': 'Admin panel language',
  'settings.adminLanguage.fieldHint': 'Applies the next time a page loads.',
  'settings.saved': 'Saved',

  // Settings — common
  'settings.common.edit': 'Edit',
  'settings.common.save': 'Save',
  'settings.common.saving': 'Saving…',
  'settings.common.cancel': 'Cancel',

  // Settings — Default site language
  'settings.language.sectionTitle': 'Language',
  'settings.language.sectionHint': 'Default language shown to visitors who have not set a preference.',
  'settings.language.fieldLabel': 'Default site language',
  'settings.language.fieldHint': 'Visitors can still switch language using the EN / KA toggle in the nav.',

  // Settings — Booking toggles
  'settings.booking.sectionTitle': 'Booking',
  'settings.booking.showPrice.label': 'Show price after company booking',
  'settings.booking.showPrice.hint': 'When on, the booking confirmation screen shows the total price for company bookings. Turn off to keep rates private.',
  'settings.booking.enhanced.label': 'Enhanced company booking form',
  'settings.booking.enhanced.hint': 'When on, company bookings on the public site show split guest counts, hot dish selection, and masterclass add-ons.',
  'settings.booking.detailedInvoice.label': 'Detailed invoice',
  'settings.booking.detailedInvoice.hint': 'When on, printed invoices show split guest counts, masterclass lines, and extras. When off, invoices show the total only.',
  'settings.booking.hideDropdown.label': 'Hide company dropdown (use code instead)',
  'settings.booking.hideDropdown.hint': 'When on, both booking and wine order forms replace the company dropdown with a direct code entry field. A "New Company?" button also appears.',

  // Settings — Payment Details
  'settings.payment.sectionTitle': 'Payment Details',
  'settings.payment.sectionHint': 'Shown on printed invoices. Changes apply to all future prints.',
  'settings.payment.recipientName': 'Recipient name',
  'settings.payment.recipientNamePh': 'e.g. I/E Elene Khundadze',
  'settings.payment.personalNumber': 'Personal ID number',
  'settings.payment.personalNumberPh': 'e.g. 01001040828',
  'settings.payment.bankName': 'Recipient bank',
  'settings.payment.bankNamePh': 'e.g. JSC TBC Bank',
  'settings.payment.bankCode': 'Bank code',
  'settings.payment.bankCodePh': 'e.g. TBCBGE22',
  'settings.payment.iban': 'Recipient IBAN',
  'settings.payment.ibanPh': 'e.g. GE65TB7183445064300079',

  // Settings — Online Payment (card payments via Flitt). Only rendered when the
  // online-payment module is on for this tenant.
  'settings.onlinePayment.sectionTitle': 'Card Payments',
  'settings.onlinePayment.sectionHint': 'Lets guests pay by card at the moment they book, instead of you arranging payment with them afterwards.',
  'settings.onlinePayment.merchantId': 'Merchant ID',
  'settings.onlinePayment.merchantIdPh': 'e.g. 4056054',
  'settings.onlinePayment.merchantIdHint': 'The account number Flitt gave you when your account was opened.',
  'settings.onlinePayment.secretKey': 'Secret key',
  'settings.onlinePayment.secretKeyPh': 'Paste the key from Flitt',
  'settings.onlinePayment.secretKeyHint': 'For safety this is never shown again once saved. Type a new key to replace the saved one, or leave this empty to keep it as it is.',
  'settings.onlinePayment.statusSet': 'Saved',
  'settings.onlinePayment.statusNotSet': 'Not set',
  'settings.onlinePayment.saveKey': 'Save key',
  'settings.onlinePayment.clear': 'Remove key',
  'settings.onlinePayment.clearConfirm': 'Remove the saved secret key? Guests will go back to placing normal reservations until you enter a new one.',
  'settings.onlinePayment.readyTitle': 'Card payments are switched on',
  'settings.onlinePayment.readyBody': 'Guests are asked to pay by card when they book. Bookings with no price set still come through as normal reservations for you to settle by hand.',
  'settings.onlinePayment.pendingTitle': 'Card payments are not active yet',
  'settings.onlinePayment.pendingBody': 'Until both boxes below are filled in, guests book exactly as they do today: they place a reservation and you arrange payment with them yourself. Nothing is broken and nobody is charged.',

  // Admin-wide warning banner — online payment is on but nothing can be charged.
  // Plan-OnlinePayment §7.3: the fallback is correct for the guest but invisible
  // to the winery, so it has to be said out loud.
  'paymentSetup.banner.title': 'Card payments are switched on, but nothing is being charged',
  'paymentSetup.banner.credentials': 'Your Flitt Merchant ID and secret key are not both filled in, so guests cannot be sent to the payment page.',
  'paymentSetup.banner.pricing': 'No visit prices are set up, so there is no amount to charge. Add your per-person prices to the "Individuals" row on the Companies page.',
  'paymentSetup.banner.effect': 'Bookings are still arriving normally as reservations — no money is being taken for them.',
  'paymentSetup.banner.goToSettings': 'Open Settings',
  'paymentSetup.banner.goToCompanies': 'Open Companies',

  // Settings — Emails
  'settings.emails.sectionTitle': 'Emails',
  'settings.emails.sectionHint': 'Default message included in invoice emails. You can edit it before each send.',
  'settings.emails.fieldLabel': 'Default invoice message',
  'settings.emails.placeholder': 'e.g. Thank you for your visit! Please find your invoice below.',

  // Settings — Booking Rules
  'settings.bookingRules.sectionTitle': 'Booking Rules',
  'settings.bookingRules.sectionHint': 'Minimum guest counts enforced on the public booking form.',
  'settings.bookingRules.tastingMin': 'Wine Tasting minimum',
  'settings.bookingRules.tastingLunchMin': 'Tasting + Lunch minimum',
  'settings.bookingRules.guests': 'guests',

  // Settings — Contact Page (map)
  'settings.contactPage.sectionTitle': 'Contact Page',
  'settings.contactPage.sectionHint': 'Map shown in the "How to Find Us" section. Click Edit to change it.',
  'settings.contactPage.mapLabel': 'Google Maps embed URL',
  'settings.contactPage.mapPlaceholder': 'https://www.google.com/maps/embed?pb=...',
  'settings.contactPage.mapHelp': 'Get this from Google Maps → Share → Embed a map → copy the {src} value.',
  'settings.contactPage.noUrlSet': 'No URL set',
  'settings.contactPage.mapError': 'Must be a Google Maps embed URL starting with https://www.google.com/maps/embed',

  // Settings — Branding
  'settings.branding.sectionTitle': 'Branding',
  'settings.branding.sectionHint': 'Logo shown in the site navigation and admin panel. Favicon shown in browser tabs.',
  'settings.branding.logoLabel': 'Logo',
  'settings.branding.logoHint': 'SVG or PNG. Must work on a light background.',
  'settings.branding.uploadLogo': 'Upload logo',
  'settings.branding.replaceLogo': 'Replace logo',
  'settings.branding.uploading': 'Uploading…',
  'settings.branding.altTextLabel': 'Alt text',
  'settings.branding.altTextPh': 'e.g. Nikalas Marani',
  'settings.branding.altTextDefaultPh': 'your logo description here',
  'settings.branding.faviconLabel': 'Favicon',
  'settings.branding.faviconHint': 'ICO or 32×32 PNG shown in browser tabs.',
  'settings.branding.uploadFavicon': 'Upload favicon',
  'settings.branding.replaceFavicon': 'Replace favicon',

  // Settings — Contact Info
  'settings.contactInfo.sectionTitle': 'Contact Info',
  'settings.contactInfo.sectionHint': 'Email, phone, address and social links shown in the site nav and footer.',
  'settings.contactInfo.email': 'Email address',
  'settings.contactInfo.emailHint': 'Shown in the nav bar and footer.',
  'settings.contactInfo.emailPh': 'your email here',
  'settings.contactInfo.phone': 'Phone number',
  'settings.contactInfo.phoneHint': 'Shown in the footer.',
  'settings.contactInfo.phonePh': 'your phone number here',
  'settings.contactInfo.address': 'Address',
  'settings.contactInfo.addressHint': 'Shown in the footer.',
  'settings.contactInfo.addressPh': 'your address here',
  'settings.contactInfo.facebook': 'Facebook URL',
  'settings.contactInfo.facebookHint': 'Link behind the Facebook icon in the nav.',
  'settings.contactInfo.facebookPh': 'your Facebook URL here',
  'settings.contactInfo.instagram': 'Instagram URL',
  'settings.contactInfo.instagramHint': 'Link behind the Instagram icon in the nav.',
  'settings.contactInfo.instagramPh': 'your Instagram URL here',

  // Settings — Closed Days
  'settings.closedDays.sectionTitle': 'Closed Days',
  'settings.closedDays.sectionHint': 'Dates when the winery is closed. Customers cannot book these dates.',
  'settings.closedDays.reasonPh': 'Reason (optional)',
  'settings.closedDays.blockDate': 'Block date',
  'settings.closedDays.none': 'No closed days set.',

  // Orders — page chrome
  'orders.pageTitle': 'Orders',
  'orders.newOrder': '+ New Order',
  'orders.booking.singular': 'booking',
  'orders.booking.plural': 'bookings',
  'orders.noOrders': 'No orders found.',
  'orders.totalRevenue': 'Total revenue',
  'orders.filtered': '(filtered)',

  // Orders — columns
  'orders.col.orderId': 'Order ID',
  'orders.col.date': 'Date',
  'orders.col.time': 'Time',
  'orders.col.contact': 'Contact',
  'orders.col.type': 'Type',
  'orders.col.company': 'Company',
  'orders.col.tasting': 'Tasting',
  'orders.col.lunch': 'Lunch',
  'orders.col.guests': 'Total guests',
  'orders.col.visit': 'Visit',
  'orders.col.masterclass': 'Masterclass',
  'orders.col.food': 'Food',
  'orders.col.total': 'Total',
  'orders.col.status': 'Status',
  'orders.col.additional': 'Additional',

  // Orders — status labels
  'orders.status.new': 'New',
  'orders.status.confirmed': 'Confirmed',
  'orders.status.invoiceSent': 'Invoice Sent',
  'orders.status.pendingPayment': 'Awaiting Payment',
  'orders.status.paid': 'Paid',
  'orders.status.completed': 'Completed',
  'orders.status.cancelled': 'Cancelled',

  // Orders — visit type / guest / booking type
  'orders.visit.tasting': 'Wine Tasting',
  'orders.visit.tastingLunch': 'Tasting + Lunch',
  'orders.guest.singular': 'guest',
  'orders.guest.plural': 'guests',
  'orders.type.company': 'Company',
  'orders.type.individual': 'Individual',
  'orders.viewDetails': 'View details',

  // Orders — row actions
  'orders.deleteConfirm': 'Delete?',
  'orders.yes': 'Yes',
  'orders.no': 'No',
  'orders.printInvoice': 'Print invoice',
  'orders.printDetailedInvoice': 'Print detailed invoice',
  'orders.sendInvoiceEmail': 'Send invoice by email',
  'orders.editOrder': 'Edit order',
  'orders.deleteOrder': 'Delete order',
  'orders.food.veg': 'Veg:',
  'orders.food.meat': 'Meat:',

  // Orders — email modal
  'orders.emailModal.title': 'Send Invoice by Email',
  'orders.emailModal.order': 'Order',
  'orders.emailModal.to': 'To',
  'orders.emailModal.invalidEmail': '⚠ Invalid email format — edit the order to fix before sending',
  'orders.emailModal.validEmail': '✓ Valid email',
  'orders.emailModal.message': 'Message (optional — edit before sending)',
  'orders.emailModal.messagePlaceholder': 'Add a personal message…',
  'orders.emailModal.invoicePreview': 'Invoice preview',
  'orders.emailModal.sendFailed': 'Failed to send. Please try again.',
  'orders.emailModal.sentSuccess': '✓ Invoice sent successfully!',
  'orders.emailModal.sending': 'Sending…',
  'orders.emailModal.sent': 'Sent ✓',
  'orders.emailModal.sendInvoice': 'Send Invoice',
  'orders.emailModal.close': 'Close',
  'orders.emailModal.cancel': 'Cancel',
  'orders.emailModal.noEmail': 'No email address on file. Edit the order to add one first.',

  // Orders — edit panel
  'orders.editPanel.title': 'Edit Order',
  'orders.editPanel.date': 'Date',
  'orders.editPanel.time': 'Time',
  'orders.editPanel.guests': 'Number of Guests',
  'orders.editPanel.firstName': 'First Name',
  'orders.editPanel.lastName': 'Last Name',
  'orders.editPanel.phone': 'Phone',
  'orders.editPanel.email': 'Email',
  'orders.editPanel.notes': 'Notes',
  'orders.editPanel.notesPlaceholder': 'Internal notes…',
  'orders.editPanel.notEditable': 'Visit type & price are not editable.',
  'orders.editPanel.notEditableDetail': 'To change them, delete this order and submit a new booking.',
  'orders.editPanel.saving': 'Saving…',
  'orders.editPanel.save': 'Save changes',
  'orders.editPanel.cancel': 'Cancel',

  // Orders — hover preview card
  'orders.preview.guests': 'GUESTS',
  'orders.preview.guide': 'Guide / Driver',
  'orders.preview.amount': 'AMOUNT',
  'orders.preview.vegetable': 'Vegetable',
  'orders.preview.meat': 'Meat',

  // Orders — filters bar
  'orders.filters.upcoming': 'Upcoming',
  'orders.filters.filters': 'Filters',
  'orders.filters.clear': 'Clear ×',
  'orders.filters.clearFilters': 'Clear filters ×',
  'orders.filters.from': 'From',
  'orders.filters.to': 'To',
  'orders.filters.filterBy': 'Filter by',
  'orders.filters.status': 'Status',
  'orders.filters.quick': 'Quick',
  'orders.filters.allBookings': 'All bookings',
  'orders.filters.individualsOnly': 'Individuals only',
  'orders.filters.allStatuses': 'All statuses',
  'orders.filters.exportCsv': 'Export CSV',
  'orders.filters.exporting': 'Exporting…',
  'orders.filters.columns': 'Columns ▾',
  'orders.filters.showHideColumns': 'SHOW / HIDE COLUMNS',
  'orders.filters.printSheet': 'Print Sheet',

  // Orders — booking sheet print
  'orders.sheet.title': 'Booking Sheet',
  'orders.sheet.generatedAt': 'Generated',
  'orders.sheet.dateRange': 'Covers',
  'orders.sheet.noOrders': 'No bookings in this range.',
  'orders.sheet.tastingGuests': 'Tasting',
  'orders.sheet.lunchGuests': 'Lunch (12+)',
  'orders.sheet.extraGuests': 'Extra (guide/driver/under 12)',
  'orders.sheet.hotDishVeg': 'Hot dish — vegetable',
  'orders.sheet.hotDishMeat': 'Hot dish — meat',
  'orders.sheet.foodNotes': 'Food notes',
  'orders.sheet.notes': 'Notes',
  'orders.sheet.contactName': 'Contact',
  'orders.sheet.contactPhone': 'Phone',
  'orders.sheet.previewTitle': 'Booking sheet preview',
  'orders.sheet.print': 'Print',
  'orders.sheet.close': 'Close',
  'orders.sheet.individual': 'Individual',

  // Orders — view toggle
  'orders.view.table': 'Table',
  'orders.view.calendar': 'Calendar',

  // Order Detail page
  'orderDetail.backToOrders': '← Back to orders',
  'orderDetail.print': 'Print',
  'orderDetail.sendInvoiceTitle': 'Send invoice by email',
  'orderDetail.noEmailTitle': 'No email address on file',
  'orderDetail.sendFailed': 'Failed to send.',

  'orderDetail.bookingInfo.title': 'Booking Info',
  'orderDetail.bookingInfo.date': 'Date',
  'orderDetail.bookingInfo.time': 'Time',
  'orderDetail.bookingInfo.visitType': 'Visit type',
  'orderDetail.bookingInfo.bookingType': 'Booking type',
  'orderDetail.bookingInfo.company': 'Company',
  'orderDetail.bookingInfo.totalGuests': 'Total guests',
  'orderDetail.bookingInfo.phone': 'Phone',
  'orderDetail.bookingInfo.email': 'Email',
  'orderDetail.bookingInfo.notes': 'Notes',

  'orderDetail.guestBreakdown.title': 'Guest Breakdown & Dishes',
  'orderDetail.guestBreakdown.noTiers': 'No price tiers found for {name}.',
  'orderDetail.guestBreakdown.noTiersDetail': 'Guest counts cannot affect the total without rates.',
  'orderDetail.guestBreakdown.addTiersLink': 'Add price tiers in Companies admin',
  'orderDetail.guestBreakdown.thenComeBack': 'then come back to save the guest breakdown.',
  'orderDetail.guestBreakdown.tastingGuests': 'Tasting guests',
  'orderDetail.guestBreakdown.lunchGuests': 'Lunch guests',
  'orderDetail.guestBreakdown.freeGuests': 'Free guests',
  'orderDetail.guestBreakdown.freeGuestsHint': 'guide / driver / under-12',
  'orderDetail.guestBreakdown.rate': 'Rate',
  'orderDetail.guestBreakdown.rateBadge': 'Tasting {t}₾/pp · Lunch {l}₾/pp',
  'orderDetail.guestBreakdown.editRates': 'Edit rates ✎',
  'orderDetail.guestBreakdown.customRates': 'Custom rates',
  'orderDetail.guestBreakdown.standardRate': '← Standard (50₾)',
  'orderDetail.guestBreakdown.tastingRatePP': 'Tasting ₾/pp',
  'orderDetail.guestBreakdown.lunchRatePP': 'Lunch ₾/pp',
  'orderDetail.guestBreakdown.hotDishVeg': 'Hot dish — Vegetable',
  'orderDetail.guestBreakdown.hotDishMeat': 'Hot dish — Meat',
  'orderDetail.guestBreakdown.none': '— None —',
  'orderDetail.guestBreakdown.noMenuItems': 'No active menu items. Add them in',
  'orderDetail.guestBreakdown.menuItemsAdminLink': 'Menu Items admin',
  'orderDetail.guestBreakdown.foodNotes': 'Food notes',
  'orderDetail.guestBreakdown.foodNotesPlaceholder': 'Allergies, preferences, kitchen notes…',
  'orderDetail.guestBreakdown.saving': 'Saving…',
  'orderDetail.guestBreakdown.saveChanges': 'Save changes',
  'orderDetail.guestBreakdown.savedOk': 'Saved ✓',

  'orderDetail.masterclass.title': 'Masterclass Add-ons',
  'orderDetail.masterclass.colItem': 'Item',
  'orderDetail.masterclass.colUnit': 'Unit',
  'orderDetail.masterclass.colQty': 'Qty',
  'orderDetail.masterclass.colPricePerUnit': '₾/unit',
  'orderDetail.masterclass.colTotal': 'Total',
  'orderDetail.masterclass.remove': 'Remove',
  'orderDetail.masterclass.none': 'No masterclass items added yet.',
  'orderDetail.masterclass.selectItem': 'Select item…',
  'orderDetail.masterclass.add': 'Add',
  'orderDetail.masterclass.cancel': 'Cancel',
  'orderDetail.masterclass.addBtn': '+ Add masterclass',
  'orderDetail.masterclass.noActiveItems': 'No active masterclass items.',
  'orderDetail.masterclass.addSomeLink': 'Add some in Masterclass admin',

  'orderDetail.extras.title': 'Extra Charges',
  'orderDetail.extras.remove': 'Remove',
  'orderDetail.extras.none': 'No extra charges added yet.',
  'orderDetail.extras.description': 'Description',
  'orderDetail.extras.descriptionPh': 'e.g. Additional wine',
  'orderDetail.extras.amount': 'Amount (₾)',
  'orderDetail.extras.add': 'Add',
  'orderDetail.extras.cancel': 'Cancel',
  'orderDetail.extras.addBtn': '+ Add extra charge',

  'orderDetail.total.title': 'Order Total',
  'orderDetail.total.tierInUse': 'Tier in use:',
  'orderDetail.total.guests': 'guests',
  'orderDetail.total.tastingLunch': 'Tasting+Lunch',
  'orderDetail.total.regFee': 'Reg fee',
  'orderDetail.total.lunchRateZero': 'Lunch rate is 0₾/pp',
  'orderDetail.total.lunchGuestWontAdd': 'will not add to the total.',
  'orderDetail.total.setLunchRateLink': 'Set the Lunch ₾/pp in Companies admin',
  'orderDetail.total.andReload': 'and reload this page.',
  'orderDetail.total.registrationFee': 'Registration fee',
  'orderDetail.total.basePriceOriginal': 'Base price (original)',
  'orderDetail.total.totalLabel': 'Total',
  'orderDetail.total.livePreview': 'Live preview — click "Save changes" above to persist.',

  // Companies page
  'companies.summary.booking': 'booking',
  'companies.summary.wineOrders': 'wine orders',
  'companies.priceForm.minGuests': 'Min guests',
  'companies.priceForm.maxGuests': 'Max guests',
  'companies.priceForm.tastingPP': 'Tasting ₾/person',
  'companies.priceForm.tastingLunchPP': 'Tasting+Lunch ₾/person',
  'companies.priceForm.flatFee': 'Flat fee ₾ (optional)',

  'companies.editPanel.title': 'Edit Company',
  'companies.editPanel.modules': 'Modules',
  'companies.editPanel.bookings': 'Bookings',
  'companies.editPanel.wineDiscount': 'Wine discount',
  'companies.editPanel.wineDiscountHint': 'Applied to all wine order totals for this company.',
  'companies.editPanel.percentOffAllWines': '% off all wines',
  'companies.editPanel.companyInfo': 'Company info',
  'companies.editPanel.companyName': 'Company name',
  'companies.editPanel.idCode': 'Identification code (ID)',
  'companies.editPanel.optional': 'Optional',
  'companies.editPanel.address': 'Address',
  'companies.editPanel.addressPh': 'Company address',
  'companies.editPanel.contactPerson': 'Contact person (auto-fills forms)',
  'companies.editPanel.fullName': 'Full name',
  'companies.editPanel.fullNamePh': 'First and last name',
  'companies.editPanel.phonePh': '+995 5XX XXX XXX',
  'companies.editPanel.emailPh': 'contact@company.ge',
  'companies.editPanel.accessCode': 'Access code',
  'companies.editPanel.accessCodeHint': 'Companies enter this on booking or wine order forms to auto-fill their details.',
  'companies.editPanel.noCodeSet': 'No code set',
  'companies.editPanel.hide': 'Hide',
  'companies.editPanel.show': 'Show',
  'companies.editPanel.copyCode': 'Copy code',
  'companies.editPanel.copied': 'Copied!',
  'companies.editPanel.copy': 'Copy',
  'companies.editPanel.generateNewCode': '↻ Generate new code',
  'companies.editPanel.mustHaveModule': 'Company must belong to at least one module.',

  'companies.priceTiers.title': 'Price tiers',
  'companies.priceTiers.showOnSiteHint': 'Tick ★ Show on site on the tier to display on the public home page. Falls back to 50₾ / 100₾ if none selected.',
  'companies.priceTiers.noCustomTiersIndividual': 'No custom tiers. Public site shows 50₾ / 100₾ defaults.',
  'companies.priceTiers.noTiersCompany': 'No price tiers yet. Individual booking rates will apply.',
  'companies.priceTiers.deleteConfirm': 'Delete this tier?',
  'companies.priceTiers.deleting': 'Deleting…',
  'companies.priceTiers.guests': 'guests',
  'companies.priceTiers.tasting': 'Tasting:',
  'companies.priceTiers.lunch': '+Lunch:',
  'companies.priceTiers.flatFeeSuffix': 'flat fee',
  'companies.priceTiers.shownOnSiteTitle': 'Shown on public site',
  'companies.priceTiers.showThisOnSiteTitle': 'Show this tier on public site',
  'companies.priceTiers.shownOnSiteBadge': 'Shown on site',
  'companies.priceTiers.showOnSiteBadge': 'Show on site',
  'companies.priceTiers.edit': 'Edit',
  'companies.priceTiers.delete': 'Delete',
  'companies.priceTiers.addTier': '+ Add tier',

  'companies.individuals.title': 'Individuals',
  'companies.individuals.publicPricing': 'Public pricing',
  'companies.individuals.shownOnSite': 'shown on site',
  'companies.individuals.defaults': '50₾ / 100₾ defaults',
  'companies.individuals.tier.singular': 'tier',
  'companies.individuals.tier.plural': 'tiers',

  'companies.addCompanyBooking': '+ Add Booking Company',
  'companies.addCompanyWineOrder': '+ Add Wine Order Company',
  'companies.newCompanyPh': 'Company name…',
  'companies.noCompaniesBooking': 'No booking companies yet. Add one above.',
  'companies.noCompaniesWineOrder': 'No wine order companies yet. Add one above.',
  'companies.idLabel': 'ID:',
  'companies.codeSet': 'Code set',
  'companies.bothModules': 'Both modules',
  'companies.deleteConfirm': 'Delete?',
  'companies.yesDelete': 'Yes, delete',
  'companies.deleting': 'Deleting…',
  'companies.wineOrdersTab.contact': 'Contact:',
  'companies.wineOrdersTab.phone': 'Phone:',
  'companies.wineOrdersTab.email': 'Email:',
  'companies.wineOrdersTab.wineDiscount': 'wine discount',
  'companies.wineOrdersTab.noContact': 'No contact info set. Click Edit to add.',

  // Wine Orders — list/table/cards
  'wineOrders.status.pending': 'Pending',
  'wineOrders.status.delivered': 'Delivered',
  'wineOrders.status.pendingPayment': 'Awaiting Payment',
  'wineOrders.status.paymentFailed': 'Payment Failed',
  'wineOrders.payment.awaitingHint': 'Sent to the payment page but not paid yet. They may still pay, or you can take payment another way.',
  'wineOrders.payment.failedHint': 'The card payment did not go through. Nothing was charged.',
  'wineOrders.payment.markPaid': 'Mark as paid',
  'wineOrders.undo': 'Undo',
  'wineOrders.revertTo': 'Revert to {label}',
  'wineOrders.advanceTo': 'Advance to {label}',
  'wineOrders.filter.all': 'All',
  'wineOrders.filter.searchPlaceholder': 'Search company…',
  'wineOrders.filter.clear': 'Clear',
  'wineOrders.noOrdersMatch': 'No orders match the filters.',
  'wineOrders.noOrdersYet': 'No wine orders yet.',
  'wineOrders.table.amount': 'Amount',
  'wineOrders.table.bottles': 'Bottles',
  'wineOrders.mode.cards': 'Cards',
  'wineOrders.mode.pack': '📦 Pack',
  'wineOrders.card.inPack': '✓ In pack',
  'wineOrders.card.addPack': '+ Pack',
  'wineOrders.total': 'total',

  // Wine Orders — Packing view
  'packing.boxMode.six.label': 'Only 6',
  'packing.boxMode.six.sub': '6-bottle boxes only',
  'packing.boxMode.twelve.label': 'Only 12',
  'packing.boxMode.twelve.sub': '12-bottle boxes only',
  'packing.boxMode.optimal.label': 'Optimal',
  'packing.boxMode.optimal.sub': 'Mix of 12 + 6 to minimise boxes',
  'packing.print': 'Print',
  'packing.totalWines': 'Total Wines',
  'packing.byCompany': 'By Company',
  'packing.bottlesTotal': 'bottles',
  'packing.boxesNeeded': 'boxes needed',
  'packing.companiesPackedSeparately': '(companies packed separately)',
  'packing.noOrdersSelected': 'No orders selected.',
  'packing.sheetTitle': 'Wine Order Packing Sheet',
  'packing.boxModeLabel': 'Box mode',
  'packing.order.singular': 'order',
  'packing.order.plural': 'orders',
  'packing.boxesTotal': 'boxes total',
  'packing.byCompanySeparate': 'BY COMPANY (each packed separately)',

  // New Order form
  'newOrder.pageTitle': 'New Order',
  'newOrder.bookingDetails.title': 'Booking Details',
  'newOrder.bookingDetails.company': 'Company',
  'newOrder.bookingDetails.individual': '— Individual —',
  'newOrder.bookingDetails.guestCount': 'Guest count',
  'newOrder.contact.title': 'Contact',
  'newOrder.contact.firstName': 'First name',
  'newOrder.contact.lastName': 'Last name',
  'newOrder.guestBreakdown.noTiers': 'No price tiers for {name}.',
  'newOrder.guestBreakdown.wontCalc': "Guest counts won't auto-calculate a price.",
  'newOrder.guestBreakdown.addTiersLink': 'Add tiers in Companies admin',
  'newOrder.total.manualRatesCompany': 'No price tiers — enter rates manually:',
  'newOrder.total.manualRatesIndividual': 'Enter rates:',
  'newOrder.total.creating': 'Creating order…',
  'newOrder.total.create': 'Create order',

  // Orders — calendar view
  'orders.calendar.mon': 'Mon',
  'orders.calendar.tue': 'Tue',
  'orders.calendar.wed': 'Wed',
  'orders.calendar.thu': 'Thu',
  'orders.calendar.fri': 'Fri',
  'orders.calendar.sat': 'Sat',
  'orders.calendar.sun': 'Sun',
  'orders.calendar.jan': 'January',
  'orders.calendar.feb': 'February',
  'orders.calendar.mar': 'March',
  'orders.calendar.apr': 'April',
  'orders.calendar.may': 'May',
  'orders.calendar.jun': 'June',
  'orders.calendar.jul': 'July',
  'orders.calendar.aug': 'August',
  'orders.calendar.sep': 'September',
  'orders.calendar.oct': 'October',
  'orders.calendar.nov': 'November',
  'orders.calendar.dec': 'December',

  // Wines page
  'wines.pageTitle': 'Wine Listings',
  'wines.count.singular': 'wine',
  'wines.count.plural': 'wines',
  'wines.inCatalogue': 'in catalogue',
  'wines.hidden': 'Hidden',
  'wines.sparkling': 'Sparkling',
  'wines.vintage.singular': 'vintage',
  'wines.vintage.plural': 'vintages',
  'wines.hideFromCatalogue': 'Hide from catalogue',
  'wines.showInCatalogue': 'Show in catalogue',
  'wines.editWine': 'Edit wine',
  'wines.confirmDelete': 'Confirm delete',
  'wines.cancel': 'Cancel',
  'wines.deleteWine': 'Delete wine',
  'wines.collapse': 'Collapse',
  'wines.expand': 'Expand',
  'wines.name': 'Name',
  'wines.namePh': 'e.g. Saperavi',
  'wines.nameKaPh': 'e.g. საფერავი',
  'wines.nameKaFallbackHint': 'Falls back to the English name if left blank',
  'wines.type': 'Type',
  'wines.sweetness': 'Sweetness',
  'wines.alcoholLevel': 'Alcohol level % (optional)',
  'wines.alcoholLevelPh': 'e.g. 13.5',
  'wines.description': 'Description / tasting notes',
  'wines.descriptionPh': 'e.g. Deep ruby colour. Notes of dark cherry, plum, and spice.',
  'wines.colorHex': 'Colour (hex)',
  'wines.productPhoto': 'Product photo',
  'wines.savingSuffix': 'saving…',
  'wines.assignedSuffix': 'assigned ✓',
  'wines.noneSuffix': 'none',
  'wines.save': 'Save',
  'wines.saving': 'Saving…',
  'wines.vintagesTitle': 'Vintages',
  'wines.noVintagesYet': 'No vintages yet — add one below so this wine appears in the catalogue.',
  'wines.year': 'Year',
  'wines.pricePerBottle': 'Price per bottle (₾)',
  'wines.bottle': 'bottle',
  'wines.vintagePhotoOverride': 'Vintage photo (overrides product photo)',
  'wines.overrideSetSuffix': 'override set ✓',
  'wines.usingProductPhotoSuffix': 'using product photo',
  'wines.visibleInCatalogue': 'Visible in catalogue',
  'wines.overrideImageBadge': 'override image',
  'wines.editVintage': 'Edit vintage',
  'wines.deleteVintage': 'Delete vintage',
  'wines.adding': 'Adding…',
  'wines.addVintage': 'Add vintage',
  'wines.newWine': 'New wine',
  'wines.pricesPerVintageHint': 'Prices are set per vintage — add a vintage after saving.',
  'wines.addWine': 'Add wine',
  'wines.uploadOnePhoto': 'Upload one or more photos',
  'wines.uploadedPhoto': 'Uploaded photo',
  'wines.deleteUploadedPhoto': 'Delete uploaded photo',
  'wines.clear': 'Clear',
  'wines.uploadFailed': 'Upload failed:',
  'wines.unknownError': 'Unknown error',
  'wines.type.RED': 'Red',
  'wines.type.WHITE': 'White',
  'wines.type.AMBER': 'Amber',
  'wines.type.ROSE': 'Rosé',
  'wines.sweetness.DRY': 'Dry',
  'wines.sweetness.SEMI_DRY': 'Semi-dry',
  'wines.sweetness.SEMI_SWEET': 'Semi-sweet',
  'wines.sweetness.SWEET': 'Sweet',
  'wines.notSpecified': 'Not specified',
  'wines.sparklingYes': 'Sparkling',
  'wines.sparklingNo': 'Still',
  'wines.characteristicsPerVintageHint': 'Type, sweetness, sparkling, and alcohol level are set per vintage below — this winery tracks them individually per year rather than once for the whole wine.',

  // Statistics page
  'statistics.noModulesEnabled': 'No modules enabled for this tenant — nothing to show statistics for.',
  'statistics.modeSwitcher.bookings': 'Bookings',
  'statistics.showHistorical': 'Show historical breakdown →',
  'statistics.backToOverview': '← Back to overview',
  'statistics.historicalAllTime': 'Historical breakdown — all time',
  'statistics.card.totalOrders': 'Total Orders',
  'statistics.card.totalRevenue': 'Total Revenue',
  'statistics.card.thisMonth': 'This Month',
  'statistics.card.avgOrderValue': 'Avg. Order Value',
  'statistics.card.allTime': 'all time',
  'statistics.card.revenueSuffix': 'revenue',
  'statistics.card.perBooking': 'per booking',
  'statistics.chart.bookingsLast6Months': 'Bookings — last 6 months',
  'statistics.chart.revenueLast6Months': 'Revenue ₾ — last 6 months',
  'statistics.tooltip.bookings': 'bookings',
  'statistics.tooltip.revenue': 'revenue',
  'statistics.breakdown.title': 'Breakdown',
  'statistics.breakdown.byVisitTypeOrders': 'By visit type (orders)',
  'statistics.breakdown.byVisitTypeRevenue': 'By visit type (revenue ₾)',
  'statistics.breakdown.byBookingTypeOrders': 'By booking type (orders)',
  'statistics.breakdown.byBookingTypeRevenue': 'By booking type (revenue ₾)',
  'statistics.tasting': 'Tasting',
  'statistics.topCompanies.title': 'Top Companies',
  'statistics.topCompanies.none': 'No company bookings yet.',
  'statistics.card.upcomingOrders': 'Upcoming Orders',
  'statistics.card.futureRevenue': 'Future Revenue',
  'statistics.card.nextOrder': 'Next Order',
  'statistics.bookingAhead.singular': '1 booking ahead',
  'statistics.bookingAhead.plural': '{n} bookings ahead',
  'statistics.inPeriod': 'in {period}',
  'statistics.noUpcomingOrders': 'No upcoming orders',
  'statistics.filters.year': 'Year',
  'statistics.filters.month': 'Month',
  'statistics.filters.allMonths': 'All months',
  'statistics.filters.allCompanies': 'All companies',
  'statistics.filters.customer': 'Customer',
  'statistics.filters.allCustomers': 'All customers',
  'statistics.clearFilters': 'Clear filters',
  'statistics.revenueByDay': 'Revenue by day — {month} {year}',
  'statistics.revenueByMonth': 'Revenue by month — {year}',
  'statistics.noDataPeriod': 'No data for this period',
  'statistics.revenueByCompany': 'Revenue by company — {period}',
  'statistics.card.activeOrders': 'Active Orders',
  'statistics.card.avgOrderValueWine': 'Avg Order Value',
  'statistics.activeOrdersSub': 'pending · confirmed · paid',
  'statistics.perWineOrder': 'per wine order',
  'statistics.topWinesRevenue': 'Top wines — revenue',
  'statistics.wineTrends': 'Wine trends — {year}',
  'statistics.bars': 'Bars',
  'statistics.trend': 'Trend',
  'statistics.noDataForYear': 'No data for {year}',
  'statistics.selectAtLeastOneWine': 'Select at least one wine above',
  'statistics.showingFullYear': 'Showing full year · bottles ordered per month',
  'statistics.bottle.singular': 'bottle',
  'statistics.bottle.plural': 'bottles',
  'statistics.topCustomers': 'Top customers — {period}',
  'statistics.noOrdersPeriod': 'No orders for this period.',
  'statistics.search': 'Search…',
  'statistics.noMatches': 'No matches',
  'statistics.month.jan': 'Jan',
  'statistics.month.feb': 'Feb',
  'statistics.month.mar': 'Mar',
  'statistics.month.apr': 'Apr',
  'statistics.month.may': 'May',
  'statistics.month.jun': 'Jun',
  'statistics.month.jul': 'Jul',
  'statistics.month.aug': 'Aug',
  'statistics.month.sep': 'Sep',
  'statistics.month.oct': 'Oct',
  'statistics.month.nov': 'Nov',
  'statistics.month.dec': 'Dec',

  // Menu Items page
  'menuItems.item.singular': 'item',
  'menuItems.item.plural': 'items',
  'menuItems.noItemsYet': 'No items yet. Add one below.',
  'menuItems.orderPh': 'Order',
  'menuItems.sortOrderTitle': 'Sort order',
  'menuItems.activeTitle': 'Active — click to deactivate',
  'menuItems.inactiveTitle': 'Inactive — click to activate',
  'menuItems.dishNamePh': 'Dish name…',
  'menuItems.addDish': 'Add dish',
  'menuItems.description': 'Manage hot dish options for the company booking form. Active items appear as dropdown choices. Use the sort order number to control the display order.',
  'menuItems.sections.vegetable': 'Vegetable Dishes',
  'menuItems.sections.meat': 'Meat Dishes',

  // Masterclass page
  'masterclass.description': 'Manage masterclass options for company bookings. The unit type controls how pricing is calculated on each order.',
  'masterclass.unitTypes': 'Unit types',
  'masterclass.col.name': 'Name',
  'masterclass.col.unitType': 'Unit type',
  'masterclass.col.price': 'Price',
  'masterclass.noItemsYet': 'No masterclass items yet. Add one below.',
  'masterclass.active': 'Active',
  'masterclass.inactive': 'Inactive',
  'masterclass.namePh': 'e.g. Churchkhela',
  'masterclass.addItem': 'Add masterclass item',

  // Site Content editor — page chrome
  'content.pageTitle': 'Site Content',
  'content.subtitle.iframeHover': 'Hover any text on the page preview to edit it inline. Changes save per field.',
  'content.subtitle.clickField': 'Click any field below to edit it. Changes save per field.',
  'content.subtitle.backgrounds': 'Choose a background image for each page. Adjust position and zoom, then save.',
  'content.view': 'View',
  'content.mode.visual': 'Visual',
  'content.mode.backgrounds': 'Backgrounds',
  'content.localeToggle.english': 'English',
  'content.localeToggle.georgian': 'Georgian',
  'content.formVariant.simple': 'Simple',
  'content.formVariant.detailed': 'Detailed',
  'content.section.home': 'Home',
  'content.section.about': 'About',
  'content.section.contact': 'Contact',
  'content.section.form': 'Booking Form',
  'content.section.nav': 'Navigation',
  'content.section.legal': 'Legal',

  // Site Content editor — field descriptor labels (Nav)
  'content.field.nav_home': 'Home link',
  'content.field.nav_about': 'About link',
  'content.field.nav_wines': 'Order Wine link',
  'content.field.nav_contact': 'Contact link',
  'content.field.nav_book': '"Book a Visit" button',

  // Site Content editor — field descriptor labels (Home)
  'content.field.home_location_eyebrow': 'Location eyebrow',
  'content.field.home_hero_subtitle': 'Hero subtitle',
  'content.field.home_book_btn': '"Book a Visit" button',
  'content.field.home_order_wine_btn': '"Order Wine" button',
  'content.field.home_package1_title': 'Package 1 — title',
  'content.field.home_package1_desc': 'Package 1 — description',
  'content.field.home_package2_title': 'Package 2 — title',
  'content.field.home_package2_desc': 'Package 2 — description',
  'content.field.home_book_heading': 'Booking section heading',
  'content.field.home_booking_intro': 'Booking intro text',

  // Site Content editor — field descriptor labels (Booking Form)
  'content.field.form_booking_type': 'Booking Type label',
  'content.field.form_individual': 'Individual Booking button',
  'content.field.form_company_type': 'Tour Company button',
  'content.field.form_visit_type': 'Visit Type label',
  'content.field.form_tasting': 'Wine Tasting option',
  'content.field.form_tasting_lunch': 'Tasting + Lunch option',
  'content.field.form_date': 'Date label',
  'content.field.form_time_slot': 'Time Slot label',
  'content.field.form_num_guests': 'Number of Guests label',
  'content.field.form_first_name': 'First Name label',
  'content.field.form_last_name': 'Last Name label',
  'content.field.form_phone': 'Phone label',
  'content.field.form_email': 'Email label',
  'content.field.form_food_notes': 'Food Notes label',
  'content.field.form_food_notes_sub': 'Food Notes subtitle',
  'content.field.form_food_notes_placeholder': 'Food Notes placeholder',
  'content.field.form_submit': 'Submit button',
  'content.field.form_cancel_policy': 'Cancellation policy text',
  'content.field.form_success_heading': 'Success heading',
  'content.field.form_success_body': 'Success body text',
  'content.field.form_guest_counts_header': 'Guest Counts header (Detailed variant)',
  'content.field.form_hot_dish_header': 'Hot Dish Selection header (Detailed variant)',
  'content.field.form_masterclass_header': 'Masterclass Add-ons header (Detailed variant)',

  // Site Content editor — field descriptor labels (About)
  'content.field.about_eyebrow': 'Eyebrow text',
  'content.field.about_heading': 'Page heading',
  'content.field.about_story_p1': 'Story — paragraph 1',
  'content.field.about_story_p2': 'Story — paragraph 2',
  'content.field.about_story_p3': 'Story — paragraph 3',
  'content.field.about_expect_heading': '"What to Expect" heading',
  'content.field.about_expect1_label': 'Expect card 1 — label',
  'content.field.about_expect1_text': 'Expect card 1 — text',
  'content.field.about_expect2_label': 'Expect card 2 — label',
  'content.field.about_expect2_text': 'Expect card 2 — text',
  'content.field.about_expect3_label': 'Expect card 3 — label',
  'content.field.about_expect3_text': 'Expect card 3 — text',
  'content.field.about_cta_text': 'CTA text',
  'content.field.about_cta_btn': 'CTA button',

  // Site Content editor — field descriptor labels (Contact)
  'content.field.contact_eyebrow': 'Eyebrow text',
  'content.field.contact_heading': 'Page heading',
  'content.field.contact_label_phone': 'Phone card — header',
  'content.field.contact_phone': 'Phone number',
  'content.field.contact_note_phone': 'Phone card — note',
  'content.field.contact_label_email': 'Email card — header',
  'content.field.contact_email': 'Email address',
  'content.field.contact_note_email': 'Email card — note',
  'content.field.contact_label_location': 'Location card — header',
  'content.field.contact_address': 'Address / Location',
  'content.field.contact_note_location': 'Location card — note',
  'content.field.contact_label_cancel': 'Cancellation card — header',
  'content.field.contact_cancel_value': 'Cancellation — value',
  'content.field.contact_note_cancel': 'Cancellation — note',
  'content.field.contact_find_us': '"How to Find Us" heading',
  'content.field.contact_map_directions': 'Map directions text',
  'content.field.contact_book_cta': 'CTA text',
  'content.field.contact_book_btn': 'CTA button',

  // Site Content editor — field descriptor labels (Legal)
  'content.field.legal_terms_body': 'Terms and conditions — full text',
  'content.field.legal_privacy_body': 'Confidentiality policy — full text',
  'content.field.legal_returns_body': 'Return conditions — full text',

  // Backgrounds tab
  'backgrounds.intro': 'Choose a background image for each page hero. Switch between Desktop and Mobile to set each independently.',
  'backgrounds.page.home': 'Home page hero',
  'backgrounds.page.about': 'About page hero',
  'backgrounds.page.contact': 'Contact page hero',
  'backgrounds.removeImage': 'Remove image',
  'backgrounds.desktop': '🖥 Desktop',
  'backgrounds.mobile': '📱 Mobile',
  'backgrounds.chooseImage': 'Choose image',
  'backgrounds.uploading': 'Uploading…',
  'backgrounds.upload': 'Upload',
  'backgrounds.previewCaption': 'Preview — {viewport} — adjust sliders then Save to apply',
  'backgrounds.previewMobile': 'mobile (390px)',
  'backgrounds.previewDesktop': 'desktop at {vw}px viewport',
  'backgrounds.horizontalPosition': 'Horizontal position',
  'backgrounds.verticalPosition': 'Vertical position',
  'backgrounds.zoom': 'Zoom',
  'backgrounds.mobileHint': 'Mobile always fills the screen first (no grey boxes), then zoom magnifies on top of that.',
  'backgrounds.unsavedChanges': 'Preview shows unsaved changes — live site still shows previous settings',
  'backgrounds.saving': 'Saving…',
  'backgrounds.saveToApply': 'Save to apply →',
  'backgrounds.savedLive': '✓ Saved (live)',

  // EditableText — shared editor chrome (Site Content editor only)
  'editable.save': 'Save',
  'editable.cancel': 'Cancel',
  'editable.saved': '✓ Saved',
  'editable.resetToDefault': '↺ Reset to default',
  'editable.resetAriaLabel': 'Reset to default: {fallback}',
  'editable.resetTooltip': 'Reset to: “{tip}”',
  'editable.editTitle': 'Edit: {label}',
}

const ka: Translations = {
  // Nav
  'nav.orders': 'შეკვეთები',
  'nav.companies': 'კომპანიები',
  'nav.statistics': 'სტატისტიკა',
  'nav.wines': 'ღვინოები',
  'nav.wineOrders': 'ღვინის შეკვეთები',
  'nav.menuItems': 'მენიუს პუნქტები',
  'nav.masterclass': 'მასტერკლასი',
  'nav.content': 'საიტის კონტენტი',
  'nav.settings': 'პარამეტრები',
  'nav.adminTag': 'ადმინი',
  'nav.platform': 'პლატფორმა',
  'nav.signOut': 'გასვლა',

  // Settings — Admin Panel Language section
  'settings.adminLanguage.sectionTitle': 'ადმინ პანელის ენა',
  'settings.adminLanguage.sectionHint': 'ენა, რომელშიც ნაჩვენებია მთელი ეს ადმინ პანელი. დაყენდება მხოლოდ აქ — პანელს შიგნით გადამრთველი არ არის.',
  'settings.adminLanguage.fieldLabel': 'ადმინ პანელის ენა',
  'settings.adminLanguage.fieldHint': 'ამოქმედდება გვერდის შემდეგი ჩატვირთვისას.',
  'settings.saved': 'შენახულია',

  // Settings — common
  'settings.common.edit': 'რედაქტირება',
  'settings.common.save': 'შენახვა',
  'settings.common.saving': 'ინახება…',
  'settings.common.cancel': 'გაუქმება',

  // Settings — Default site language
  'settings.language.sectionTitle': 'ენა',
  'settings.language.sectionHint': 'ნაგულისხმევი ენა სტუმრებისთვის, რომლებმაც არჩევანი არ გაუკეთებიათ.',
  'settings.language.fieldLabel': 'საიტის ნაგულისხმევი ენა',
  'settings.language.fieldHint': 'სტუმრებს კვლავ შეუძლიათ ენის შეცვლა ნავიგაციაში EN / KA გადამრთველით.',

  // Settings — Booking toggles
  'settings.booking.sectionTitle': 'ჯავშანი',
  'settings.booking.showPrice.label': 'კომპანიის ჯავშნის შემდეგ ფასის ჩვენება',
  'settings.booking.showPrice.hint': 'ჩართვისას, ჯავშნის დადასტურების ეკრანი აჩვენებს კომპანიის ჯავშნის სრულ ღირებულებას. გამორთეთ, რომ ტარიფები კონფიდენციალური დარჩეს.',
  'settings.booking.enhanced.label': 'გაუმჯობესებული კომპანიის ჯავშნის ფორმა',
  'settings.booking.enhanced.hint': 'ჩართვისას, საჯარო საიტზე კომპანიის ჯავშნები აჩვენებს სტუმრების დაყოფილ რაოდენობას, ცხელი კერძის არჩევანს და მასტერკლასის დამატებებს.',
  'settings.booking.detailedInvoice.label': 'დეტალური ინვოისი',
  'settings.booking.detailedInvoice.hint': 'ჩართვისას, დაბეჭდილი ინვოისები აჩვენებს სტუმრების დაყოფილ რაოდენობას, მასტერკლასის ხაზებს და დამატებებს. გამორთვისას, ინვოისები აჩვენებს მხოლოდ ჯამს.',
  'settings.booking.hideDropdown.label': 'კომპანიის ჩამოსაშლელის დამალვა (კოდის გამოყენება)',
  'settings.booking.hideDropdown.hint': 'ჩართვისას, როგორც ჯავშნის, ისე ღვინის შეკვეთის ფორმებში კომპანიის ჩამოსაშლელი იცვლება პირდაპირი კოდის შეყვანის ველით. ასევე გამოჩნდება ღილაკი „ახალი კომპანია?“.',

  // Settings — Payment Details
  'settings.payment.sectionTitle': 'გადახდის დეტალები',
  'settings.payment.sectionHint': 'ნაჩვენებია დაბეჭდილ ინვოისებზე. ცვლილებები ვრცელდება ყველა მომდევნო ბეჭდვაზე.',
  'settings.payment.recipientName': 'მიმღების სახელი',
  'settings.payment.recipientNamePh': 'მაგ. ი/მ ელენე ხუნდაძე',
  'settings.payment.personalNumber': 'პირადი ნომერი',
  'settings.payment.personalNumberPh': 'მაგ. 01001040828',
  'settings.payment.bankName': 'მიმღები ბანკი',
  'settings.payment.bankNamePh': 'მაგ. სს „თიბისი ბანკი“',
  'settings.payment.bankCode': 'საბანკო კოდი',
  'settings.payment.bankCodePh': 'მაგ. TBCBGE22',
  'settings.payment.iban': 'მიმღების IBAN',
  'settings.payment.ibanPh': 'მაგ. GE65TB7183445064300079',

  // Settings — ონლაინ გადახდა (Flitt)
  'settings.onlinePayment.sectionTitle': 'ბარათით გადახდა',
  'settings.onlinePayment.sectionHint': 'საშუალებას აძლევს სტუმრებს გადაიხადონ ბარათით ჯავშნის გაკეთებისთანავე, იმის ნაცვლად რომ გადახდაზე შემდეგ შეთანხმდეთ.',
  'settings.onlinePayment.merchantId': 'მერჩანტის ID',
  'settings.onlinePayment.merchantIdPh': 'მაგ. 4056054',
  'settings.onlinePayment.merchantIdHint': 'ანგარიშის ნომერი, რომელიც Flitt-მა მოგცათ ანგარიშის გახსნისას.',
  'settings.onlinePayment.secretKey': 'საიდუმლო გასაღები',
  'settings.onlinePayment.secretKeyPh': 'ჩასვით Flitt-ის გასაღები',
  'settings.onlinePayment.secretKeyHint': 'უსაფრთხოებისთვის შენახვის შემდეგ ის აღარ ჩანს. ჩაწერეთ ახალი გასაღები ძველის ჩასანაცვლებლად, ან დატოვეთ ცარიელი, რომ არსებული უცვლელი დარჩეს.',
  'settings.onlinePayment.statusSet': 'შენახულია',
  'settings.onlinePayment.statusNotSet': 'არ არის მითითებული',
  'settings.onlinePayment.saveKey': 'გასაღების შენახვა',
  'settings.onlinePayment.clear': 'გასაღების წაშლა',
  'settings.onlinePayment.clearConfirm': 'წავშალოთ შენახული საიდუმლო გასაღები? სტუმრები დაუბრუნდებიან ჩვეულებრივ ჯავშანს, სანამ ახალს არ შეიყვანთ.',
  'settings.onlinePayment.readyTitle': 'ბარათით გადახდა ჩართულია',
  'settings.onlinePayment.readyBody': 'სტუმრებს ჯავშნისას ეთხოვებათ ბარათით გადახდა. ჯავშნები, რომლებსაც ფასი არ აქვთ, მაინც ჩვეულებრივ ჯავშნად შემოვა და ხელით უნდა დაარეგულიროთ.',
  'settings.onlinePayment.pendingTitle': 'ბარათით გადახდა ჯერ არ არის აქტიური',
  'settings.onlinePayment.pendingBody': 'სანამ ორივე ველი არ შეივსება, სტუმრები ჯავშნიან ისე, როგორც დღეს: აკეთებენ ჯავშანს და გადახდაზე თქვენ თვითონ თანხმდებით. არაფერია გაფუჭებული და არავის ერიცხება თანხა.',

  // ადმინის გაფრთხილება — ონლაინ გადახდა ჩართულია, მაგრამ თანხა არ ირიცხება
  'paymentSetup.banner.title': 'ბარათით გადახდა ჩართულია, მაგრამ თანხა არ ირიცხება',
  'paymentSetup.banner.credentials': 'Flitt-ის მერჩანტის ID და საიდუმლო გასაღები ორივე არ არის შევსებული, ამიტომ სტუმრები ვერ გადადიან გადახდის გვერდზე.',
  'paymentSetup.banner.pricing': 'ვიზიტის ფასები არ არის მითითებული, ამიტომ ჩამოსაჭრელი თანხა არ არსებობს. დაამატეთ ფასები ერთ სტუმარზე „ინდივიდუალურის“ სტრიქონში კომპანიების გვერდზე.',
  'paymentSetup.banner.effect': 'ჯავშნები კვლავ ჩვეულებრივად შემოდის — მათზე თანხა არ ირიცხება.',
  'paymentSetup.banner.goToSettings': 'პარამეტრების გახსნა',
  'paymentSetup.banner.goToCompanies': 'კომპანიების გახსნა',

  // Settings — Emails
  'settings.emails.sectionTitle': 'ელ-ფოსტები',
  'settings.emails.sectionHint': 'ნაგულისხმევი შეტყობინება, რომელიც ერთვის ინვოისის ელ-წერილებს. გაგზავნამდე შეგიძლიათ შეასწოროთ.',
  'settings.emails.fieldLabel': 'ინვოისის ნაგულისხმევი შეტყობინება',
  'settings.emails.placeholder': 'მაგ. გმადლობთ ვიზიტისთვის! თქვენი ინვოისი იხილეთ ქვემოთ.',

  // Settings — Booking Rules
  'settings.bookingRules.sectionTitle': 'ჯავშნის წესები',
  'settings.bookingRules.sectionHint': 'მინიმალური სტუმრების რაოდენობა, რომელიც მოქმედებს საჯარო ჯავშნის ფორმაზე.',
  'settings.bookingRules.tastingMin': 'ღვინის დეგუსტაციის მინიმუმი',
  'settings.bookingRules.tastingLunchMin': 'დეგუსტაცია + სადილის მინიმუმი',
  'settings.bookingRules.guests': 'სტუმარი',

  // Settings — Contact Page (map)
  'settings.contactPage.sectionTitle': 'საკონტაქტო გვერდი',
  'settings.contactPage.sectionHint': 'რუკა, რომელიც ნაჩვენებია განყოფილებაში „როგორ მოგვინახოთ“. შესაცვლელად დააჭირეთ „რედაქტირება“-ს.',
  'settings.contactPage.mapLabel': 'Google Maps ჩაშენების URL',
  'settings.contactPage.mapPlaceholder': 'https://www.google.com/maps/embed?pb=...',
  'settings.contactPage.mapHelp': 'ეს მიიღეთ Google Maps-იდან → Share → Embed a map → დააკოპირეთ {src} მნიშვნელობა.',
  'settings.contactPage.noUrlSet': 'URL არ არის მითითებული',
  'settings.contactPage.mapError': 'უნდა იყოს Google Maps-ის ჩაშენების URL, რომელიც იწყება https://www.google.com/maps/embed-ით',

  // Settings — Branding
  'settings.branding.sectionTitle': 'ბრენდინგი',
  'settings.branding.sectionHint': 'ლოგო ჩანს საიტის ნავიგაციასა და ადმინ პანელში. ფავიკონი ჩანს ბრაუზერის ჩანართებში.',
  'settings.branding.logoLabel': 'ლოგო',
  'settings.branding.logoHint': 'SVG ან PNG. უნდა გამოჩნდეს ღია ფონზე.',
  'settings.branding.uploadLogo': 'ლოგოს ატვირთვა',
  'settings.branding.replaceLogo': 'ლოგოს შეცვლა',
  'settings.branding.uploading': 'იტვირთება…',
  'settings.branding.altTextLabel': 'ალტ ტექსტი',
  'settings.branding.altTextPh': 'მაგ. ნიკალას მარანი',
  'settings.branding.altTextDefaultPh': 'თქვენი ლოგოს აღწერა აქ',
  'settings.branding.faviconLabel': 'ფავიკონი',
  'settings.branding.faviconHint': 'ICO ან 32×32 PNG, რომელიც ჩანს ბრაუზერის ჩანართებში.',
  'settings.branding.uploadFavicon': 'ფავიკონის ატვირთვა',
  'settings.branding.replaceFavicon': 'ფავიკონის შეცვლა',

  // Settings — Contact Info
  'settings.contactInfo.sectionTitle': 'საკონტაქტო ინფორმაცია',
  'settings.contactInfo.sectionHint': 'ელ-ფოსტა, ტელეფონი, მისამართი და სოციალური ბმულები, რომლებიც ჩანს საიტის ნავიგაციასა და ფუტერში.',
  'settings.contactInfo.email': 'ელ-ფოსტის მისამართი',
  'settings.contactInfo.emailHint': 'ჩანს ნავიგაციასა და ფუტერში.',
  'settings.contactInfo.emailPh': 'თქვენი ელ-ფოსტა აქ',
  'settings.contactInfo.phone': 'ტელეფონის ნომერი',
  'settings.contactInfo.phoneHint': 'ჩანს ფუტერში.',
  'settings.contactInfo.phonePh': 'თქვენი ტელეფონის ნომერი აქ',
  'settings.contactInfo.address': 'მისამართი',
  'settings.contactInfo.addressHint': 'ჩანს ფუტერში.',
  'settings.contactInfo.addressPh': 'თქვენი მისამართი აქ',
  'settings.contactInfo.facebook': 'Facebook-ის URL',
  'settings.contactInfo.facebookHint': 'ბმული Facebook-ის ხატულაზე ნავიგაციაში.',
  'settings.contactInfo.facebookPh': 'თქვენი Facebook-ის URL აქ',
  'settings.contactInfo.instagram': 'Instagram-ის URL',
  'settings.contactInfo.instagramHint': 'ბმული Instagram-ის ხატულაზე ნავიგაციაში.',
  'settings.contactInfo.instagramPh': 'თქვენი Instagram-ის URL აქ',

  // Settings — Closed Days
  'settings.closedDays.sectionTitle': 'დახურული დღეები',
  'settings.closedDays.sectionHint': 'თარიღები, როდესაც მარანი დახურულია. მომხმარებლებს არ შეუძლიათ ამ თარიღებზე ჯავშნის გაკეთება.',
  'settings.closedDays.reasonPh': 'მიზეზი (არასავალდებულო)',
  'settings.closedDays.blockDate': 'თარიღის დაბლოკვა',
  'settings.closedDays.none': 'დახურული დღეები არ არის მითითებული.',

  // Orders — page chrome
  'orders.pageTitle': 'შეკვეთები',
  'orders.newOrder': '+ ახალი შეკვეთა',
  'orders.booking.singular': 'ჯავშანი',
  'orders.booking.plural': 'ჯავშანი',
  'orders.noOrders': 'შეკვეთები ვერ მოიძებნა.',
  'orders.totalRevenue': 'ჯამური შემოსავალი',
  'orders.filtered': '(გაფილტრული)',

  // Orders — columns
  'orders.col.orderId': 'შეკვეთის ID',
  'orders.col.date': 'თარიღი',
  'orders.col.time': 'დრო',
  'orders.col.contact': 'კონტაქტი',
  'orders.col.type': 'ტიპი',
  'orders.col.company': 'კომპანია',
  'orders.col.tasting': 'დეგუსტაცია',
  'orders.col.lunch': 'სადილი',
  'orders.col.guests': 'სულ სტუმარი',
  'orders.col.visit': 'ვიზიტი',
  'orders.col.masterclass': 'მასტერკლასი',
  'orders.col.food': 'საკვები',
  'orders.col.total': 'ჯამი',
  'orders.col.status': 'სტატუსი',
  'orders.col.additional': 'დამატებითი',

  // Orders — status labels
  'orders.status.new': 'ახალი',
  'orders.status.confirmed': 'დადასტურებული',
  'orders.status.invoiceSent': 'ინვოისი გაგზავნილია',
  'orders.status.pendingPayment': 'გადახდის მოლოდინში',
  'orders.status.paid': 'გადახდილი',
  'orders.status.completed': 'დასრულებული',
  'orders.status.cancelled': 'გაუქმებული',

  // Orders — visit type / guest / booking type
  'orders.visit.tasting': 'ღვინის დეგუსტაცია',
  'orders.visit.tastingLunch': 'დეგუსტაცია + სადილი',
  'orders.guest.singular': 'სტუმარი',
  'orders.guest.plural': 'სტუმარი',
  'orders.type.company': 'კომპანია',
  'orders.type.individual': 'ინდივიდუალური',
  'orders.viewDetails': 'დეტალების ნახვა',

  // Orders — row actions
  'orders.deleteConfirm': 'წაშლა?',
  'orders.yes': 'დიახ',
  'orders.no': 'არა',
  'orders.printInvoice': 'ინვოისის ბეჭდვა',
  'orders.printDetailedInvoice': 'დეტალური ინვოისის ბეჭდვა',
  'orders.sendInvoiceEmail': 'ინვოისის გაგზავნა ელ-ფოსტით',
  'orders.editOrder': 'შეკვეთის რედაქტირება',
  'orders.deleteOrder': 'შეკვეთის წაშლა',
  'orders.food.veg': 'მცენარეული:',
  'orders.food.meat': 'ხორცი:',

  // Orders — email modal
  'orders.emailModal.title': 'ინვოისის გაგზავნა ელ-ფოსტით',
  'orders.emailModal.order': 'შეკვეთა',
  'orders.emailModal.to': 'მიმღები',
  'orders.emailModal.invalidEmail': '⚠ ელ-ფოსტის არასწორი ფორმატი — გაგზავნამდე შეასწორეთ შეკვეთაში',
  'orders.emailModal.validEmail': '✓ ელ-ფოსტა სწორია',
  'orders.emailModal.message': 'შეტყობინება (არასავალდებულო — გაგზავნამდე შეგიძლიათ შეასწოროთ)',
  'orders.emailModal.messagePlaceholder': 'დაამატეთ პირადი შეტყობინება…',
  'orders.emailModal.invoicePreview': 'ინვოისის გადახედვა',
  'orders.emailModal.sendFailed': 'გაგზავნა ვერ მოხერხდა. სცადეთ თავიდან.',
  'orders.emailModal.sentSuccess': '✓ ინვოისი წარმატებით გაიგზავნა!',
  'orders.emailModal.sending': 'იგზავნება…',
  'orders.emailModal.sent': 'გაიგზავნა ✓',
  'orders.emailModal.sendInvoice': 'ინვოისის გაგზავნა',
  'orders.emailModal.close': 'დახურვა',
  'orders.emailModal.cancel': 'გაუქმება',
  'orders.emailModal.noEmail': 'ელ-ფოსტის მისამართი მითითებული არ არის. ჯერ დაამატეთ შეკვეთის რედაქტირებით.',

  // Orders — edit panel
  'orders.editPanel.title': 'შეკვეთის რედაქტირება',
  'orders.editPanel.date': 'თარიღი',
  'orders.editPanel.time': 'დრო',
  'orders.editPanel.guests': 'სტუმრების რაოდენობა',
  'orders.editPanel.firstName': 'სახელი',
  'orders.editPanel.lastName': 'გვარი',
  'orders.editPanel.phone': 'ტელეფონი',
  'orders.editPanel.email': 'ელ-ფოსტა',
  'orders.editPanel.notes': 'შენიშვნები',
  'orders.editPanel.notesPlaceholder': 'შიდა შენიშვნები…',
  'orders.editPanel.notEditable': 'ვიზიტის ტიპი და ფასი არ ექვემდებარება რედაქტირებას.',
  'orders.editPanel.notEditableDetail': 'შესაცვლელად წაშალეთ ეს შეკვეთა და გააკეთეთ ახალი ჯავშანი.',
  'orders.editPanel.saving': 'ინახება…',
  'orders.editPanel.save': 'ცვლილებების შენახვა',
  'orders.editPanel.cancel': 'გაუქმება',

  // Orders — hover preview card
  'orders.preview.guests': 'სტუმრები',
  'orders.preview.guide': 'გიდი / მძღოლი',
  'orders.preview.amount': 'თანხა',
  'orders.preview.vegetable': 'მცენარეული',
  'orders.preview.meat': 'ხორცი',

  // Orders — filters bar
  'orders.filters.upcoming': 'მოახლოებული',
  'orders.filters.filters': 'ფილტრები',
  'orders.filters.clear': 'გასუფთავება ×',
  'orders.filters.clearFilters': 'ფილტრების გასუფთავება ×',
  'orders.filters.from': 'დან',
  'orders.filters.to': 'მდე',
  'orders.filters.filterBy': 'ფილტრი',
  'orders.filters.status': 'სტატუსი',
  'orders.filters.quick': 'სწრაფი',
  'orders.filters.allBookings': 'ყველა ჯავშანი',
  'orders.filters.individualsOnly': 'მხოლოდ ინდივიდუალური',
  'orders.filters.allStatuses': 'ყველა სტატუსი',
  'orders.filters.exportCsv': 'CSV ექსპორტი',
  'orders.filters.exporting': 'გადის ექსპორტი…',
  'orders.filters.columns': 'სვეტები ▾',
  'orders.filters.showHideColumns': 'სვეტების ჩვენება/დამალვა',
  'orders.filters.printSheet': 'ცხრილის ბეჭდვა',

  // Orders — booking sheet print
  'orders.sheet.title': 'ჯავშნების ცხრილი',
  'orders.sheet.generatedAt': 'შექმნილია',
  'orders.sheet.dateRange': 'მოიცავს',
  'orders.sheet.noOrders': 'ამ პერიოდში ჯავშნები არ არის.',
  'orders.sheet.tastingGuests': 'დეგუსტაცია',
  'orders.sheet.lunchGuests': 'სადილი (12+)',
  'orders.sheet.extraGuests': 'დამატებითი (გიდი/მძღოლი/12 წლამდე)',
  'orders.sheet.hotDishVeg': 'ცხელი კერძი — ბოსტნეული',
  'orders.sheet.hotDishMeat': 'ცხელი კერძი — ხორცი',
  'orders.sheet.foodNotes': 'შენიშვნა კვებაზე',
  'orders.sheet.notes': 'შენიშვნა',
  'orders.sheet.contactName': 'საკონტაქტო პირი',
  'orders.sheet.contactPhone': 'ტელეფონი',
  'orders.sheet.previewTitle': 'ჯავშნების ცხრილის გადახედვა',
  'orders.sheet.print': 'ბეჭდვა',
  'orders.sheet.close': 'დახურვა',
  'orders.sheet.individual': 'ინდივიდუალური',

  // Orders — view toggle
  'orders.view.table': 'ცხრილი',
  'orders.view.calendar': 'კალენდარი',

  // Order Detail page
  'orderDetail.backToOrders': '← შეკვეთებზე დაბრუნება',
  'orderDetail.print': 'ბეჭდვა',
  'orderDetail.sendInvoiceTitle': 'ინვოისის გაგზავნა ელ-ფოსტით',
  'orderDetail.noEmailTitle': 'ელ-ფოსტის მისამართი მითითებული არ არის',
  'orderDetail.sendFailed': 'გაგზავნა ვერ მოხერხდა.',

  'orderDetail.bookingInfo.title': 'ჯავშნის ინფორმაცია',
  'orderDetail.bookingInfo.date': 'თარიღი',
  'orderDetail.bookingInfo.time': 'დრო',
  'orderDetail.bookingInfo.visitType': 'ვიზიტის ტიპი',
  'orderDetail.bookingInfo.bookingType': 'ჯავშნის ტიპი',
  'orderDetail.bookingInfo.company': 'კომპანია',
  'orderDetail.bookingInfo.totalGuests': 'სულ სტუმარი',
  'orderDetail.bookingInfo.phone': 'ტელეფონი',
  'orderDetail.bookingInfo.email': 'ელ-ფოსტა',
  'orderDetail.bookingInfo.notes': 'შენიშვნები',

  'orderDetail.guestBreakdown.title': 'სტუმრების დაყოფა და კერძები',
  'orderDetail.guestBreakdown.noTiers': '{name}-ს ფასების კატეგორია არ მოიძებნა.',
  'orderDetail.guestBreakdown.noTiersDetail': 'სტუმრების რაოდენობა ვერ იმოქმედებს ჯამზე ტარიფების გარეშე.',
  'orderDetail.guestBreakdown.addTiersLink': 'დაამატეთ ფასების კატეგორია კომპანიების ადმინში',
  'orderDetail.guestBreakdown.thenComeBack': 'შემდეგ დაბრუნდით სტუმრების დაყოფის შესანახად.',
  'orderDetail.guestBreakdown.tastingGuests': 'დეგუსტაციის სტუმარი',
  'orderDetail.guestBreakdown.lunchGuests': 'სადილის სტუმარი',
  'orderDetail.guestBreakdown.freeGuests': 'უფასო სტუმარი',
  'orderDetail.guestBreakdown.freeGuestsHint': 'გიდი / მძღოლი / 12 წლამდე',
  'orderDetail.guestBreakdown.rate': 'ტარიფი',
  'orderDetail.guestBreakdown.rateBadge': 'დეგუსტაცია {t}₾/პ · სადილი {l}₾/პ',
  'orderDetail.guestBreakdown.editRates': 'ტარიფების რედაქტირება ✎',
  'orderDetail.guestBreakdown.customRates': 'საკუთარი ტარიფები',
  'orderDetail.guestBreakdown.standardRate': '← სტანდარტული (50₾)',
  'orderDetail.guestBreakdown.tastingRatePP': 'დეგუსტაცია ₾/პ',
  'orderDetail.guestBreakdown.lunchRatePP': 'სადილი ₾/პ',
  'orderDetail.guestBreakdown.hotDishVeg': 'ცხელი კერძი — მცენარეული',
  'orderDetail.guestBreakdown.hotDishMeat': 'ცხელი კერძი — ხორცი',
  'orderDetail.guestBreakdown.none': '— არცერთი —',
  'orderDetail.guestBreakdown.noMenuItems': 'აქტიური მენიუს პუნქტები არ არის. დაამატეთ',
  'orderDetail.guestBreakdown.menuItemsAdminLink': 'მენიუს პუნქტების ადმინში',
  'orderDetail.guestBreakdown.foodNotes': 'შენიშვნები კვებაზე',
  'orderDetail.guestBreakdown.foodNotesPlaceholder': 'ალერგია, უპირატესობები, შენიშვნები სამზარეულოსთვის…',
  'orderDetail.guestBreakdown.saving': 'ინახება…',
  'orderDetail.guestBreakdown.saveChanges': 'ცვლილებების შენახვა',
  'orderDetail.guestBreakdown.savedOk': 'შენახულია ✓',

  'orderDetail.masterclass.title': 'მასტერკლასის დამატებები',
  'orderDetail.masterclass.colItem': 'პუნქტი',
  'orderDetail.masterclass.colUnit': 'ერთეული',
  'orderDetail.masterclass.colQty': 'რაოდ.',
  'orderDetail.masterclass.colPricePerUnit': '₾/ერთეული',
  'orderDetail.masterclass.colTotal': 'ჯამი',
  'orderDetail.masterclass.remove': 'წაშლა',
  'orderDetail.masterclass.none': 'მასტერკლასის პუნქტები ჯერ არ დამატებულა.',
  'orderDetail.masterclass.selectItem': 'აირჩიეთ პუნქტი…',
  'orderDetail.masterclass.add': 'დამატება',
  'orderDetail.masterclass.cancel': 'გაუქმება',
  'orderDetail.masterclass.addBtn': '+ მასტერკლასის დამატება',
  'orderDetail.masterclass.noActiveItems': 'აქტიური მასტერკლასის პუნქტები არ არის.',
  'orderDetail.masterclass.addSomeLink': 'დაამატეთ მასტერკლასის ადმინში',

  'orderDetail.extras.title': 'დამატებითი ხარჯები',
  'orderDetail.extras.remove': 'წაშლა',
  'orderDetail.extras.none': 'დამატებითი ხარჯები ჯერ არ დამატებულა.',
  'orderDetail.extras.description': 'აღწერა',
  'orderDetail.extras.descriptionPh': 'მაგ. დამატებითი ღვინო',
  'orderDetail.extras.amount': 'თანხა (₾)',
  'orderDetail.extras.add': 'დამატება',
  'orderDetail.extras.cancel': 'გაუქმება',
  'orderDetail.extras.addBtn': '+ დამატებითი ხარჯის დამატება',

  'orderDetail.total.title': 'შეკვეთის ჯამი',
  'orderDetail.total.tierInUse': 'გამოყენებული კატეგორია:',
  'orderDetail.total.guests': 'სტუმარი',
  'orderDetail.total.tastingLunch': 'დეგუსტაცია+სადილი',
  'orderDetail.total.regFee': 'რეგისტრაციის საფასური',
  'orderDetail.total.lunchRateZero': 'სადილის ტარიფია 0₾/პ',
  'orderDetail.total.lunchGuestWontAdd': 'ჯამს არ დაემატება.',
  'orderDetail.total.setLunchRateLink': 'დააყენეთ სადილის ₾/პ კომპანიების ადმინში',
  'orderDetail.total.andReload': 'და გადატვირთეთ ეს გვერდი.',
  'orderDetail.total.registrationFee': 'რეგისტრაციის საფასური',
  'orderDetail.total.basePriceOriginal': 'საბაზისო ფასი (თავდაპირველი)',
  'orderDetail.total.totalLabel': 'ჯამი',
  'orderDetail.total.livePreview': 'ცოცხალი გადახედვა — დააჭირეთ „ცვლილებების შენახვას“ ზემოთ შესანახად.',

  // Companies page
  'companies.summary.booking': 'ჯავშანი',
  'companies.summary.wineOrders': 'ღვინის შეკვეთა',
  'companies.priceForm.minGuests': 'მინ. სტუმარი',
  'companies.priceForm.maxGuests': 'მაქს. სტუმარი',
  'companies.priceForm.tastingPP': 'დეგუსტაცია ₾/პერსონა',
  'companies.priceForm.tastingLunchPP': 'დეგუსტაცია+სადილი ₾/პერსონა',
  'companies.priceForm.flatFee': 'ფიქსირებული საფასური ₾ (არასავალდებულო)',

  'companies.editPanel.title': 'კომპანიის რედაქტირება',
  'companies.editPanel.modules': 'მოდულები',
  'companies.editPanel.bookings': 'ჯავშნები',
  'companies.editPanel.wineDiscount': 'ღვინის ფასდაკლება',
  'companies.editPanel.wineDiscountHint': 'ვრცელდება ამ კომპანიის ყველა ღვინის შეკვეთის ჯამზე.',
  'companies.editPanel.percentOffAllWines': '% ფასდაკლება ყველა ღვინოზე',
  'companies.editPanel.companyInfo': 'კომპანიის ინფორმაცია',
  'companies.editPanel.companyName': 'კომპანიის სახელი',
  'companies.editPanel.idCode': 'საიდენტიფიკაციო კოდი (ID)',
  'companies.editPanel.optional': 'არასავალდებულო',
  'companies.editPanel.address': 'მისამართი',
  'companies.editPanel.addressPh': 'კომპანიის მისამართი',
  'companies.editPanel.contactPerson': 'საკონტაქტო პირი (ავტომატურად ავსებს ფორმებს)',
  'companies.editPanel.fullName': 'სრული სახელი',
  'companies.editPanel.fullNamePh': 'სახელი და გვარი',
  'companies.editPanel.phonePh': '+995 5XX XXX XXX',
  'companies.editPanel.emailPh': 'contact@company.ge',
  'companies.editPanel.accessCode': 'წვდომის კოდი',
  'companies.editPanel.accessCodeHint': 'კომპანიები შეყავთ ამ კოდს ჯავშნის ან ღვინის შეკვეთის ფორმებში, რომ ავტომატურად შეივსოს მათი მონაცემები.',
  'companies.editPanel.noCodeSet': 'კოდი არ არის მითითებული',
  'companies.editPanel.hide': 'დამალვა',
  'companies.editPanel.show': 'ჩვენება',
  'companies.editPanel.copyCode': 'კოდის კოპირება',
  'companies.editPanel.copied': 'დაკოპირდა!',
  'companies.editPanel.copy': 'კოპირება',
  'companies.editPanel.generateNewCode': '↻ ახალი კოდის გენერაცია',
  'companies.editPanel.mustHaveModule': 'კომპანია უნდა მიეკუთვნებოდეს მინიმუმ ერთ მოდულს.',

  'companies.priceTiers.title': 'ფასების კატეგორიები',
  'companies.priceTiers.showOnSiteHint': 'მონიშნეთ ★ საიტზე ჩვენება კატეგორიაზე, რომ გამოჩნდეს საჯარო მთავარ გვერდზე. თუ არცერთი არჩეული არ არის, გამოჩნდება 50₾ / 100₾ ნაგულისხმევი.',
  'companies.priceTiers.noCustomTiersIndividual': 'საკუთარი კატეგორია არ არის. საჯარო საიტი აჩვენებს 50₾ / 100₾ ნაგულისხმევს.',
  'companies.priceTiers.noTiersCompany': 'ფასების კატეგორია ჯერ არ არის. გამოყენებული იქნება ინდივიდუალური ჯავშნის ტარიფები.',
  'companies.priceTiers.deleteConfirm': 'წავშალოთ ეს კატეგორია?',
  'companies.priceTiers.deleting': 'იშლება…',
  'companies.priceTiers.guests': 'სტუმარი',
  'companies.priceTiers.tasting': 'დეგუსტაცია:',
  'companies.priceTiers.lunch': '+სადილი:',
  'companies.priceTiers.flatFeeSuffix': 'ფიქსირებული საფასური',
  'companies.priceTiers.shownOnSiteTitle': 'ჩანს საჯარო საიტზე',
  'companies.priceTiers.showThisOnSiteTitle': 'ამ კატეგორიის საიტზე ჩვენება',
  'companies.priceTiers.shownOnSiteBadge': 'ჩანს საიტზე',
  'companies.priceTiers.showOnSiteBadge': 'საიტზე ჩვენება',
  'companies.priceTiers.edit': 'რედაქტირება',
  'companies.priceTiers.delete': 'წაშლა',
  'companies.priceTiers.addTier': '+ კატეგორიის დამატება',

  'companies.individuals.title': 'ინდივიდუალური',
  'companies.individuals.publicPricing': 'საჯარო ფასები',
  'companies.individuals.shownOnSite': 'ჩანს საიტზე',
  'companies.individuals.defaults': '50₾ / 100₾ ნაგულისხმევი',
  'companies.individuals.tier.singular': 'კატეგორია',
  'companies.individuals.tier.plural': 'კატეგორია',

  'companies.addCompanyBooking': '+ ჯავშნის კომპანიის დამატება',
  'companies.addCompanyWineOrder': '+ ღვინის შეკვეთის კომპანიის დამატება',
  'companies.newCompanyPh': 'კომპანიის სახელი…',
  'companies.noCompaniesBooking': 'ჯავშნის კომპანია ჯერ არ არის. დაამატეთ ზემოთ.',
  'companies.noCompaniesWineOrder': 'ღვინის შეკვეთის კომპანია ჯერ არ არის. დაამატეთ ზემოთ.',
  'companies.idLabel': 'ID:',
  'companies.codeSet': 'კოდი მითითებულია',
  'companies.bothModules': 'ორივე მოდული',
  'companies.deleteConfirm': 'წაშლა?',
  'companies.yesDelete': 'დიახ, წაშლა',
  'companies.deleting': 'იშლება…',
  'companies.wineOrdersTab.contact': 'კონტაქტი:',
  'companies.wineOrdersTab.phone': 'ტელეფონი:',
  'companies.wineOrdersTab.email': 'ელ-ფოსტა:',
  'companies.wineOrdersTab.wineDiscount': 'ღვინის ფასდაკლება',
  'companies.wineOrdersTab.noContact': 'საკონტაქტო ინფორმაცია არ არის მითითებული. დააჭირეთ რედაქტირებას დასამატებლად.',

  // Wine Orders — list/table/cards
  'wineOrders.status.pending': 'მოლოდინში',
  'wineOrders.status.delivered': 'მიწოდებული',
  'wineOrders.status.pendingPayment': 'გადახდის მოლოდინში',
  'wineOrders.status.paymentFailed': 'გადახდა ვერ შესრულდა',
  'wineOrders.payment.awaitingHint': 'გადახდის გვერდზე გადავიდა, მაგრამ ჯერ არ გადაუხდია. შესაძლოა მოგვიანებით გადაიხადოს, ან სხვა გზით მიიღოთ თანხა.',
  'wineOrders.payment.failedHint': 'ბარათით გადახდა ვერ შესრულდა. თანხა არ ჩამოჭრილა.',
  'wineOrders.payment.markPaid': 'გადახდილად მონიშვნა',
  'wineOrders.undo': 'დაბრუნება',
  'wineOrders.revertTo': 'დაბრუნება {label}-ზე',
  'wineOrders.advanceTo': 'გადასვლა {label}-ზე',
  'wineOrders.filter.all': 'ყველა',
  'wineOrders.filter.searchPlaceholder': 'მოძებნეთ კომპანია…',
  'wineOrders.filter.clear': 'გასუფთავება',
  'wineOrders.noOrdersMatch': 'ფილტრებით შეკვეთა ვერ მოიძებნა.',
  'wineOrders.noOrdersYet': 'ღვინის შეკვეთები ჯერ არ არის.',
  'wineOrders.table.amount': 'თანხა',
  'wineOrders.table.bottles': 'ბოთლი',
  'wineOrders.mode.cards': 'ბარათები',
  'wineOrders.mode.pack': '📦 შეფუთვა',
  'wineOrders.card.inPack': '✓ შეფუთვაშია',
  'wineOrders.card.addPack': '+ შეფუთვა',
  'wineOrders.total': 'სულ',

  // Wine Orders — Packing view
  'packing.boxMode.six.label': 'მხოლოდ 6',
  'packing.boxMode.six.sub': 'მხოლოდ 6-ბოთლიანი ყუთები',
  'packing.boxMode.twelve.label': 'მხოლოდ 12',
  'packing.boxMode.twelve.sub': 'მხოლოდ 12-ბოთლიანი ყუთები',
  'packing.boxMode.optimal.label': 'ოპტიმალური',
  'packing.boxMode.optimal.sub': '12 + 6-ის კომბინაცია ყუთების მინიმუმისთვის',
  'packing.print': 'ბეჭდვა',
  'packing.totalWines': 'სულ ღვინოები',
  'packing.byCompany': 'კომპანიების მიხედვით',
  'packing.bottlesTotal': 'ბოთლი',
  'packing.boxesNeeded': 'ყუთი საჭირო',
  'packing.companiesPackedSeparately': '(კომპანიები ცალ-ცალკე იფუთება)',
  'packing.noOrdersSelected': 'შეკვეთა არჩეული არ არის.',
  'packing.sheetTitle': 'ღვინის შეკვეთის შეფუთვის ფურცელი',
  'packing.boxModeLabel': 'ყუთის რეჟიმი',
  'packing.order.singular': 'შეკვეთა',
  'packing.order.plural': 'შეკვეთა',
  'packing.boxesTotal': 'ყუთი სულ',
  'packing.byCompanySeparate': 'კომპანიების მიხედვით (თითოეული ცალ-ცალკე იფუთება)',

  // New Order form
  'newOrder.pageTitle': 'ახალი შეკვეთა',
  'newOrder.bookingDetails.title': 'ჯავშნის დეტალები',
  'newOrder.bookingDetails.company': 'კომპანია',
  'newOrder.bookingDetails.individual': '— ინდივიდუალური —',
  'newOrder.bookingDetails.guestCount': 'სტუმრების რაოდენობა',
  'newOrder.contact.title': 'კონტაქტი',
  'newOrder.contact.firstName': 'სახელი',
  'newOrder.contact.lastName': 'გვარი',
  'newOrder.guestBreakdown.noTiers': '{name}-ს ფასების კატეგორია არ აქვს.',
  'newOrder.guestBreakdown.wontCalc': 'სტუმრების რაოდენობა ავტომატურად ვერ გამოთვლის ფასს.',
  'newOrder.guestBreakdown.addTiersLink': 'დაამატეთ კატეგორია კომპანიების ადმინში',
  'newOrder.total.manualRatesCompany': 'ფასების კატეგორია არ არის — შეიყვანეთ ტარიფები ხელით:',
  'newOrder.total.manualRatesIndividual': 'შეიყვანეთ ტარიფები:',
  'newOrder.total.creating': 'შეკვეთა იქმნება…',
  'newOrder.total.create': 'შეკვეთის შექმნა',

  // Orders — calendar view
  'orders.calendar.mon': 'ორშ',
  'orders.calendar.tue': 'სამ',
  'orders.calendar.wed': 'ოთხ',
  'orders.calendar.thu': 'ხუთ',
  'orders.calendar.fri': 'პარ',
  'orders.calendar.sat': 'შაბ',
  'orders.calendar.sun': 'კვი',
  'orders.calendar.jan': 'იანვარი',
  'orders.calendar.feb': 'თებერვალი',
  'orders.calendar.mar': 'მარტი',
  'orders.calendar.apr': 'აპრილი',
  'orders.calendar.may': 'მაისი',
  'orders.calendar.jun': 'ივნისი',
  'orders.calendar.jul': 'ივლისი',
  'orders.calendar.aug': 'აგვისტო',
  'orders.calendar.sep': 'სექტემბერი',
  'orders.calendar.oct': 'ოქტომბერი',
  'orders.calendar.nov': 'ნოემბერი',
  'orders.calendar.dec': 'დეკემბერი',

  // Wines page
  'wines.pageTitle': 'ღვინოების ჩამონათვალი',
  'wines.count.singular': 'ღვინო',
  'wines.count.plural': 'ღვინო',
  'wines.inCatalogue': 'კატალოგში',
  'wines.hidden': 'დამალული',
  'wines.sparkling': 'ცქრიალა',
  'wines.vintage.singular': 'რთველი',
  'wines.vintage.plural': 'რთველი',
  'wines.hideFromCatalogue': 'კატალოგიდან დამალვა',
  'wines.showInCatalogue': 'კატალოგში ჩვენება',
  'wines.editWine': 'ღვინის რედაქტირება',
  'wines.confirmDelete': 'წაშლის დადასტურება',
  'wines.cancel': 'გაუქმება',
  'wines.deleteWine': 'ღვინის წაშლა',
  'wines.collapse': 'ჩაკეცვა',
  'wines.expand': 'გაშლა',
  'wines.name': 'სახელი',
  'wines.namePh': 'მაგ. საფერავი',
  'wines.nameKaPh': 'მაგ. საფერავი',
  'wines.nameKaFallbackHint': 'თუ ცარიელია, გამოჩნდება ინგლისური სახელი',
  'wines.type': 'ტიპი',
  'wines.sweetness': 'სიტკბოება',
  'wines.alcoholLevel': 'ალკოჰოლის % (არასავალდებულო)',
  'wines.alcoholLevelPh': 'მაგ. 13.5',
  'wines.description': 'აღწერა / დეგუსტაციის შენიშვნები',
  'wines.descriptionPh': 'მაგ. ღრმა ბუნიკისფერი. ალუბლის, ქლიავისა და სანელებლების ტონები.',
  'wines.colorHex': 'ფერი (hex)',
  'wines.productPhoto': 'პროდუქტის ფოტო',
  'wines.savingSuffix': 'ინახება…',
  'wines.assignedSuffix': 'მინიჭებულია ✓',
  'wines.noneSuffix': 'არცერთი',
  'wines.save': 'შენახვა',
  'wines.saving': 'ინახება…',
  'wines.vintagesTitle': 'რთველები',
  'wines.noVintagesYet': 'რთველი ჯერ არ არის — დაამატეთ ქვემოთ, რომ ეს ღვინო კატალოგში გამოჩნდეს.',
  'wines.year': 'წელი',
  'wines.pricePerBottle': 'ფასი ბოთლზე (₾)',
  'wines.bottle': 'ბოთლი',
  'wines.vintagePhotoOverride': 'რთველის ფოტო (გადაფარავს პროდუქტის ფოტოს)',
  'wines.overrideSetSuffix': 'გადაფარვა დაყენებულია ✓',
  'wines.usingProductPhotoSuffix': 'გამოიყენება პროდუქტის ფოტო',
  'wines.visibleInCatalogue': 'ჩანს კატალოგში',
  'wines.overrideImageBadge': 'გადაფარული ფოტო',
  'wines.editVintage': 'რთველის რედაქტირება',
  'wines.deleteVintage': 'რთველის წაშლა',
  'wines.adding': 'ემატება…',
  'wines.addVintage': 'რთველის დამატება',
  'wines.newWine': 'ახალი ღვინო',
  'wines.pricesPerVintageHint': 'ფასები დგინდება რთველის მიხედვით — შენახვის შემდეგ დაამატეთ რთველი.',
  'wines.addWine': 'ღვინის დამატება',
  'wines.uploadOnePhoto': 'ერთი ან მეტი ფოტოს ატვირთვა',
  'wines.uploadedPhoto': 'ატვირთული ფოტო',
  'wines.deleteUploadedPhoto': 'ატვირთული ფოტოს წაშლა',
  'wines.clear': 'გასუფთავება',
  'wines.uploadFailed': 'ატვირთვა ვერ მოხერხდა:',
  'wines.unknownError': 'უცნობი შეცდომა',
  'wines.type.RED': 'წითელი',
  'wines.type.WHITE': 'თეთრი',
  'wines.type.AMBER': 'ქარვისფერი',
  'wines.type.ROSE': 'ვარდისფერი',
  'wines.sweetness.DRY': 'მშრალი',
  'wines.sweetness.SEMI_DRY': 'ნახევრად მშრალი',
  'wines.sweetness.SEMI_SWEET': 'ნახევრად ტკბილი',
  'wines.sweetness.SWEET': 'ტკბილი',
  'wines.notSpecified': 'არ არის მითითებული',
  'wines.sparklingYes': 'ცქრიალა',
  'wines.sparklingNo': 'უბრალო',
  'wines.characteristicsPerVintageHint': 'ტიპი, სიტკბო, ცქრიალა და ალკოჰოლის დონე დგინდება თითოეული რთველისთვის ცალ-ცალკე, ქვემოთ — ეს ღვინის სახლი ამ მონაცემებს ინახავს წლების მიხედვით, ერთიანად ღვინოზე კი არა.',

  // Statistics page
  'statistics.noModulesEnabled': 'ამ ტენანტისთვის მოდულები ჩართული არ არის — სტატისტიკის საჩვენებელი არაფერია.',
  'statistics.modeSwitcher.bookings': 'ჯავშნები',
  'statistics.showHistorical': 'ისტორიული მონაცემების ჩვენება →',
  'statistics.backToOverview': '← მიმოხილვას დაბრუნება',
  'statistics.historicalAllTime': 'ისტორიული მონაცემები — მთელი პერიოდი',
  'statistics.card.totalOrders': 'სულ შეკვეთა',
  'statistics.card.totalRevenue': 'სულ შემოსავალი',
  'statistics.card.thisMonth': 'ამ თვეს',
  'statistics.card.avgOrderValue': 'საშ. შეკვეთის ღირებულება',
  'statistics.card.allTime': 'მთელი პერიოდი',
  'statistics.card.revenueSuffix': 'შემოსავალი',
  'statistics.card.perBooking': 'ჯავშანზე',
  'statistics.chart.bookingsLast6Months': 'ჯავშნები — ბოლო 6 თვე',
  'statistics.chart.revenueLast6Months': 'შემოსავალი ₾ — ბოლო 6 თვე',
  'statistics.tooltip.bookings': 'ჯავშანი',
  'statistics.tooltip.revenue': 'შემოსავალი',
  'statistics.breakdown.title': 'დაყოფა',
  'statistics.breakdown.byVisitTypeOrders': 'ვიზიტის ტიპის მიხედვით (შეკვეთა)',
  'statistics.breakdown.byVisitTypeRevenue': 'ვიზიტის ტიპის მიხედვით (შემოსავალი ₾)',
  'statistics.breakdown.byBookingTypeOrders': 'ჯავშნის ტიპის მიხედვით (შეკვეთა)',
  'statistics.breakdown.byBookingTypeRevenue': 'ჯავშნის ტიპის მიხედვით (შემოსავალი ₾)',
  'statistics.tasting': 'დეგუსტაცია',
  'statistics.topCompanies.title': 'წამყვანი კომპანიები',
  'statistics.topCompanies.none': 'კომპანიის ჯავშანი ჯერ არ არის.',
  'statistics.card.upcomingOrders': 'მოახლოებული შეკვეთები',
  'statistics.card.futureRevenue': 'მომავალი შემოსავალი',
  'statistics.card.nextOrder': 'შემდეგი შეკვეთა',
  'statistics.bookingAhead.singular': '1 მოახლოებული ჯავშანი',
  'statistics.bookingAhead.plural': '{n} მოახლოებული ჯავშანი',
  'statistics.inPeriod': '{period}-ში',
  'statistics.noUpcomingOrders': 'მოახლოებული შეკვეთა არ არის',
  'statistics.filters.year': 'წელი',
  'statistics.filters.month': 'თვე',
  'statistics.filters.allMonths': 'ყველა თვე',
  'statistics.filters.allCompanies': 'ყველა კომპანია',
  'statistics.filters.customer': 'მომხმარებელი',
  'statistics.filters.allCustomers': 'ყველა მომხმარებელი',
  'statistics.clearFilters': 'ფილტრების გასუფთავება',
  'statistics.revenueByDay': 'შემოსავალი დღეების მიხედვით — {month} {year}',
  'statistics.revenueByMonth': 'შემოსავალი თვეების მიხედვით — {year}',
  'statistics.noDataPeriod': 'ამ პერიოდისთვის მონაცემები არ არის',
  'statistics.revenueByCompany': 'შემოსავალი კომპანიების მიხედვით — {period}',
  'statistics.card.activeOrders': 'აქტიური შეკვეთები',
  'statistics.card.avgOrderValueWine': 'საშ. შეკვეთის ღირებულება',
  'statistics.activeOrdersSub': 'მოლოდინში · დადასტურებული · გადახდილი',
  'statistics.perWineOrder': 'ღვინის შეკვეთაზე',
  'statistics.topWinesRevenue': 'ტოპ ღვინოები — შემოსავალი',
  'statistics.wineTrends': 'ღვინის ტენდენციები — {year}',
  'statistics.bars': 'სვეტები',
  'statistics.trend': 'ტენდენცია',
  'statistics.noDataForYear': '{year}-ისთვის მონაცემები არ არის',
  'statistics.selectAtLeastOneWine': 'აირჩიეთ მინიმუმ ერთი ღვინო ზემოთ',
  'statistics.showingFullYear': 'ნაჩვენებია მთელი წელი · ბოთლების რაოდენობა თვეების მიხედვით',
  'statistics.bottle.singular': 'ბოთლი',
  'statistics.bottle.plural': 'ბოთლი',
  'statistics.topCustomers': 'წამყვანი მომხმარებლები — {period}',
  'statistics.noOrdersPeriod': 'ამ პერიოდში შეკვეთა არ არის.',
  'statistics.search': 'ძიება…',
  'statistics.noMatches': 'დამთხვევა ვერ მოიძებნა',
  'statistics.month.jan': 'იან',
  'statistics.month.feb': 'თებ',
  'statistics.month.mar': 'მარ',
  'statistics.month.apr': 'აპრ',
  'statistics.month.may': 'მაი',
  'statistics.month.jun': 'ივნ',
  'statistics.month.jul': 'ივლ',
  'statistics.month.aug': 'აგვ',
  'statistics.month.sep': 'სექ',
  'statistics.month.oct': 'ოქტ',
  'statistics.month.nov': 'ნოე',
  'statistics.month.dec': 'დეკ',

  // Menu Items page
  'menuItems.item.singular': 'პუნქტი',
  'menuItems.item.plural': 'პუნქტი',
  'menuItems.noItemsYet': 'პუნქტები ჯერ არ არის. დაამატეთ ქვემოთ.',
  'menuItems.orderPh': 'რიგი',
  'menuItems.sortOrderTitle': 'დალაგების რიგი',
  'menuItems.activeTitle': 'აქტიური — დაწკაპეთ დეაქტივაციისთვის',
  'menuItems.inactiveTitle': 'არააქტიური — დაწკაპეთ გასააქტიურებლად',
  'menuItems.dishNamePh': 'კერძის სახელი…',
  'menuItems.addDish': 'კერძის დამატება',
  'menuItems.description': 'მართეთ ცხელი კერძის ვარიანტები კომპანიის ჯავშნის ფორმისთვის. აქტიური პუნქტები ჩანს ჩამოსაშლელ სიაში. გამოიყენეთ დალაგების რიგის ნომერი ჩვენების თანმიმდევრობის სამართავად.',
  'menuItems.sections.vegetable': 'მცენარეული კერძები',
  'menuItems.sections.meat': 'ხორცის კერძები',

  // Masterclass page
  'masterclass.description': 'მართეთ მასტერკლასის ვარიანტები კომპანიის ჯავშნებისთვის. ერთეულის ტიპი განსაზღვრავს, როგორ გამოითვლება ფასი თითოეულ შეკვეთაზე.',
  'masterclass.unitTypes': 'ერთეულის ტიპები',
  'masterclass.col.name': 'სახელი',
  'masterclass.col.unitType': 'ერთეულის ტიპი',
  'masterclass.col.price': 'ფასი',
  'masterclass.noItemsYet': 'მასტერკლასის პუნქტები ჯერ არ არის. დაამატეთ ქვემოთ.',
  'masterclass.active': 'აქტიური',
  'masterclass.inactive': 'არააქტიური',
  'masterclass.namePh': 'მაგ. ჩურჩხელა',
  'masterclass.addItem': 'მასტერკლასის პუნქტის დამატება',

  // Site Content editor — page chrome
  'content.pageTitle': 'საიტის კონტენტი',
  'content.subtitle.iframeHover': 'დააჰოვერეთ ნებისმიერ ტექსტზე გვერდის გადახედვაში მის პირდაპირ რედაქტირებისთვის. ცვლილებები ინახება თითოეული ველისთვის ცალ-ცალკე.',
  'content.subtitle.clickField': 'დააწკაპუნეთ ნებისმიერ ველზე ქვემოთ მის რედაქტირებისთვის. ცვლილებები ინახება თითოეული ველისთვის ცალ-ცალკე.',
  'content.subtitle.backgrounds': 'აირჩიეთ ფონის სურათი თითოეული გვერდისთვის. დაარეგულირეთ პოზიცია და გადიდება, შემდეგ შეინახეთ.',
  'content.view': 'ხედი',
  'content.mode.visual': 'ვიზუალური',
  'content.mode.backgrounds': 'ფონები',
  'content.localeToggle.english': 'ინგლისური',
  'content.localeToggle.georgian': 'ქართული',
  'content.formVariant.simple': 'მარტივი',
  'content.formVariant.detailed': 'დეტალური',
  'content.section.home': 'მთავარი',
  'content.section.about': 'ჩვენ შესახებ',
  'content.section.contact': 'კონტაქტი',
  'content.section.form': 'ჯავშნის ფორმა',
  'content.section.nav': 'ნავიგაცია',
  'content.section.legal': 'იურიდიული',

  // Site Content editor — field descriptor labels (Nav)
  'content.field.nav_home': 'ბმული „მთავარი“',
  'content.field.nav_about': 'ბმული „ჩვენ შესახებ“',
  'content.field.nav_wines': 'ბმული „ღვინის შეკვეთა“',
  'content.field.nav_contact': 'ბმული „კონტაქტი“',
  'content.field.nav_book': 'ღილაკი „ვიზიტის დაჯავშნა“',

  // Site Content editor — field descriptor labels (Home)
  'content.field.home_location_eyebrow': 'მდებარეობის ზედწერილი',
  'content.field.home_hero_subtitle': 'მთავარი ქვესათაური',
  'content.field.home_book_btn': 'ღილაკი „ვიზიტის დაჯავშნა“',
  'content.field.home_order_wine_btn': 'ღილაკი „ღვინის შეკვეთა“',
  'content.field.home_package1_title': 'პაკეტი 1 — სათაური',
  'content.field.home_package1_desc': 'პაკეტი 1 — აღწერა',
  'content.field.home_package2_title': 'პაკეტი 2 — სათაური',
  'content.field.home_package2_desc': 'პაკეტი 2 — აღწერა',
  'content.field.home_book_heading': 'ჯავშნის სექციის სათაური',
  'content.field.home_booking_intro': 'ჯავშნის შესავალი ტექსტი',

  // Site Content editor — field descriptor labels (Booking Form)
  'content.field.form_booking_type': 'ჯავშნის ტიპის ლეიბლი',
  'content.field.form_individual': 'ღილაკი „ინდივიდუალური ჯავშანი“',
  'content.field.form_company_type': 'ღილაკი „ტურისტული კომპანია“',
  'content.field.form_visit_type': 'ვიზიტის ტიპის ლეიბლი',
  'content.field.form_tasting': 'ვარიანტი „ღვინის დეგუსტაცია“',
  'content.field.form_tasting_lunch': 'ვარიანტი „დეგუსტაცია + სადილი“',
  'content.field.form_date': 'თარიღის ლეიბლი',
  'content.field.form_time_slot': 'დროის ინტერვალის ლეიბლი',
  'content.field.form_num_guests': 'სტუმრების რაოდენობის ლეიბლი',
  'content.field.form_first_name': 'სახელის ლეიბლი',
  'content.field.form_last_name': 'გვარის ლეიბლი',
  'content.field.form_phone': 'ტელეფონის ლეიბლი',
  'content.field.form_email': 'ელფოსტის ლეიბლი',
  'content.field.form_food_notes': 'კვების შენიშვნების ლეიბლი',
  'content.field.form_food_notes_sub': 'კვების შენიშვნების ქვეტექსტი',
  'content.field.form_food_notes_placeholder': 'კვების შენიშვნების placeholder',
  'content.field.form_submit': 'გაგზავნის ღილაკი',
  'content.field.form_cancel_policy': 'გაუქმების პოლიტიკის ტექსტი',
  'content.field.form_success_heading': 'წარმატების სათაური',
  'content.field.form_success_body': 'წარმატების ტექსტი',
  'content.field.form_guest_counts_header': 'სტუმრების რაოდენობის სათაური (დეტალური ვარიანტი)',
  'content.field.form_hot_dish_header': 'ცხელი კერძის სათაური (დეტალური ვარიანტი)',
  'content.field.form_masterclass_header': 'მასტერკლასის სათაური (დეტალური ვარიანტი)',

  // Site Content editor — field descriptor labels (About)
  'content.field.about_eyebrow': 'ზედწერილი',
  'content.field.about_heading': 'გვერდის სათაური',
  'content.field.about_story_p1': 'ისტორია — აბზაცი 1',
  'content.field.about_story_p2': 'ისტორია — აბზაცი 2',
  'content.field.about_story_p3': 'ისტორია — აბზაცი 3',
  'content.field.about_expect_heading': 'სათაური „რას უნდა ელოდოთ“',
  'content.field.about_expect1_label': 'ბარათი 1 — ლეიბლი',
  'content.field.about_expect1_text': 'ბარათი 1 — ტექსტი',
  'content.field.about_expect2_label': 'ბარათი 2 — ლეიბლი',
  'content.field.about_expect2_text': 'ბარათი 2 — ტექსტი',
  'content.field.about_expect3_label': 'ბარათი 3 — ლეიბლი',
  'content.field.about_expect3_text': 'ბარათი 3 — ტექსტი',
  'content.field.about_cta_text': 'CTA ტექსტი',
  'content.field.about_cta_btn': 'CTA ღილაკი',

  // Site Content editor — field descriptor labels (Contact)
  'content.field.contact_eyebrow': 'ზედწერილი',
  'content.field.contact_heading': 'გვერდის სათაური',
  'content.field.contact_label_phone': 'ტელეფონის ბარათი — სათაური',
  'content.field.contact_phone': 'ტელეფონის ნომერი',
  'content.field.contact_note_phone': 'ტელეფონის ბარათი — შენიშვნა',
  'content.field.contact_label_email': 'ელფოსტის ბარათი — სათაური',
  'content.field.contact_email': 'ელფოსტის მისამართი',
  'content.field.contact_note_email': 'ელფოსტის ბარათი — შენიშვნა',
  'content.field.contact_label_location': 'მდებარეობის ბარათი — სათაური',
  'content.field.contact_address': 'მისამართი / მდებარეობა',
  'content.field.contact_note_location': 'მდებარეობის ბარათი — შენიშვნა',
  'content.field.contact_label_cancel': 'გაუქმების ბარათი — სათაური',
  'content.field.contact_cancel_value': 'გაუქმება — მნიშვნელობა',
  'content.field.contact_note_cancel': 'გაუქმების ბარათი — შენიშვნა',
  'content.field.contact_find_us': 'სათაური „როგორ გვიპოვოთ“',
  'content.field.contact_map_directions': 'რუკის მიმართულებების ტექსტი',
  'content.field.contact_book_cta': 'CTA ტექსტი',
  'content.field.contact_book_btn': 'CTA ღილაკი',

  // Site Content editor — field descriptor labels (Legal)
  'content.field.legal_terms_body': 'წესები და პირობები — სრული ტექსტი',
  'content.field.legal_privacy_body': 'კონფიდენციალურობის პოლიტიკა — სრული ტექსტი',
  'content.field.legal_returns_body': 'დაბრუნების პირობები — სრული ტექსტი',

  // Backgrounds tab
  'backgrounds.intro': 'აირჩიეთ ფონის სურათი თითოეული გვერდის hero-სთვის. გადართეთ დესქტოპსა და მობილურს შორის დამოუკიდებლად დასაყენებლად.',
  'backgrounds.page.home': 'მთავარი გვერდის hero',
  'backgrounds.page.about': '„ჩვენ შესახებ“ გვერდის hero',
  'backgrounds.page.contact': 'კონტაქტის გვერდის hero',
  'backgrounds.removeImage': 'სურათის წაშლა',
  'backgrounds.desktop': '🖥 დესქტოპი',
  'backgrounds.mobile': '📱 მობილური',
  'backgrounds.chooseImage': 'აირჩიეთ სურათი',
  'backgrounds.uploading': 'იტვირთება…',
  'backgrounds.upload': 'ატვირთვა',
  'backgrounds.previewCaption': 'გადახედვა — {viewport} — დაარეგულირეთ სლაიდერები და შემდეგ შეინახეთ',
  'backgrounds.previewMobile': 'მობილური (390px)',
  'backgrounds.previewDesktop': 'დესქტოპი {vw}px ხედში',
  'backgrounds.horizontalPosition': 'ჰორიზონტალური პოზიცია',
  'backgrounds.verticalPosition': 'ვერტიკალური პოზიცია',
  'backgrounds.zoom': 'გადიდება',
  'backgrounds.mobileHint': 'მობილურზე სურათი ჯერ ავსებს მთელ ეკრანს (ნაცრისფერი არეები არ იქნება), შემდეგ ამაზე ემატება გადიდება.',
  'backgrounds.unsavedChanges': 'გადახედვაში ჩანს შეუნახავი ცვლილებები — ცოცხალ საიტზე კვლავ წინა პარამეტრებია',
  'backgrounds.saving': 'ინახება…',
  'backgrounds.saveToApply': 'შეინახეთ გასააქტიურებლად →',
  'backgrounds.savedLive': '✓ შენახულია (ცოცხალი)',

  // EditableText — shared editor chrome (Site Content editor only)
  'editable.save': 'შენახვა',
  'editable.cancel': 'გაუქმება',
  'editable.saved': '✓ შენახულია',
  'editable.resetToDefault': '↺ ნაგულისხმევზე დაბრუნება',
  'editable.resetAriaLabel': 'ნაგულისხმევზე დაბრუნება: {fallback}',
  'editable.resetTooltip': 'დაბრუნება: „{tip}“',
  'editable.editTitle': 'რედაქტირება: {label}',
}

const dict: Record<string, Translations> = { en, ka }

export function adminT(locale: string, key: string, vars?: Record<string, string | number>): string {
  let str = dict[locale]?.[key] ?? dict.en[key] ?? key
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replaceAll(`{${k}}`, String(v))
    }
  }
  return str
}
